#!/usr/bin/env python3
"""H4c: Perivascular niche mapping — S-panel.

Map vascular (Endothelial) cell density per ROI; test whether specific
immune subsets cluster near vessels using KDTree nearest-neighbor distances.

Tests:
  1. Endothelial fraction per ROI — distribution across cohort
  2. Mean distance to nearest vessel by immune cell type (which cells are closest?)
  3. Correlation: endothelial fraction vs immune cell type fractions
  4. Endothelial density in follicular vs interfollicular domains
  5. Leave-one-TMA-out sensitivity
  6. Driver analysis (cell type correlations with endothelial fraction)
"""

import os, sys
import numpy as np
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from scipy.stats import spearmanr, mannwhitneyu, kruskal
from scipy.spatial import KDTree
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from run_hypotheses_v2 import (
    load_array, get_marker_idx, load_marker, is_tumor_core, get_tumor_mask,
    classify_domains, compute_roi_celltype_fractions, correlate_celltype_with_metric,
    add_cartoon, label_panel, plot_representative_core_spatial
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OUTPUT_DIR = 'output/hypotheses_v8'
CARTOON_DIR = 'output/hypothesis_cartoons'
S_PANEL_PATH = 'output/all_TMA_S_global_v8.h5ad'
S_UTAG_PATH = 'output/all_TMA_S_utag_ct_merged.h5ad'
MIN_CELLS = 5000  # S-panel min typed cells
MIN_ENDO = 5      # min endothelial cells per ROI for KDTree
TMA_COLORS = {'A1': '#3498db', 'B1': '#e74c3c', 'C1': '#2ecc71', 'Biomax': '#f39c12'}

# Immune cell types to measure distance to vessels
IMMUNE_TYPES = [
    'CD4 T cells', 'CD8 T cells', 'Macrophages', 'M1 Macrophages',
    'M2 Macrophages', 'Dendritic cells', 'FDC', 'Myeloid (S100A9+)', 'pDC'
]

LQ_TYPES = {'Low quality / Unassigned'}


def generate_cartoon():
    """Generate concept cartoon for H4c using Gemini image generation."""
    cartoon_path = os.path.join(CARTOON_DIR, 'h4c_perivascular.png')
    if os.path.exists(cartoon_path):
        print(f"Cartoon already exists: {cartoon_path}")
        return cartoon_path

    os.makedirs(CARTOON_DIR, exist_ok=True)
    try:
        from google import genai
        from google.genai import types
        from PIL import Image as PILImage
        import io

        client = genai.Client(api_key=os.environ['GEMINI_API_KEY'])
        prompt = (
            "Scientific concept illustration for a research paper. "
            "Show a cross-section of tissue with blood vessels (red/pink tubes with "
            "CD31/CD34 labeled endothelial cells lining the vessel walls). "
            "Around the vessels, show immune cells clustering at different distances: "
            "macrophages (green) and dendritic cells (orange) closest to the vessels, "
            "T cells (blue) at intermediate distance, and B cells (purple) further away "
            "in follicle-like structures. "
            "Use arrows showing distance measurements from immune cells to the nearest vessel. "
            "Label: 'Perivascular Niche' near the vessels. "
            "Clean, schematic style suitable for a biology journal. White background. "
            "No text overlapping with cells."
        )
        response = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(number_of_images=1)
        )
        if response.generated_images:
            img_bytes = response.generated_images[0].image.image_bytes
            img = PILImage.open(io.BytesIO(img_bytes))
            img.save(cartoon_path, format='PNG')
            print(f"Cartoon saved: {cartoon_path}")
        else:
            print("WARNING: No images generated by Gemini")
    except Exception as e:
        print(f"WARNING: Could not generate cartoon: {e}")

    return cartoon_path


def run_h4c():
    print(f"\n{'='*70}")
    print(f"H4c: Perivascular Niche Mapping — S-panel")
    print(f"{'='*70}")

    # --- Load data ---
    f = h5py.File(S_PANEL_PATH, 'r')
    f_utag = h5py.File(S_UTAG_PATH, 'r')

    sample_ids = load_array(f, 'sample_id')
    tma_arr = load_array(f, 'tma')
    cell_types = load_array(f, 'cell_type')
    tumor_mask = get_tumor_mask(sample_ids)
    cx = f['obs']['centroid_x'][:]
    cy = f['obs']['centroid_y'][:]

    n_total = len(sample_ids)
    n_tumor = np.sum(tumor_mask)
    print(f"S-panel: {n_total:,} total -> {n_tumor:,} tumor cells")

    # Cell type breakdown
    is_endo = cell_types == 'Endothelial'
    n_endo = np.sum(is_endo & tumor_mask)
    print(f"Endothelial cells (tumor): {n_endo:,}")

    # Domains
    print(f"\nClassifying domains...")
    domains, foll_domains, inter_domains = classify_domains(f_utag, cell_types, 'S')
    foll_mask = np.isin(domains, foll_domains) & tumor_mask
    inter_mask = np.isin(domains, inter_domains) & tumor_mask

    # Non-LQ mask
    non_lq = tumor_mask & ~np.isin(cell_types, list(LQ_TYPES))

    # ---------------------------------------------------------------------------
    # 1. Per-ROI endothelial fraction
    # ---------------------------------------------------------------------------
    print(f"\n--- Per-ROI Endothelial Fraction ---")

    unique_rois = sorted(set(sample_ids[tumor_mask]))
    roi_endo_frac = {}
    roi_endo_count = {}
    roi_tma = {}
    roi_typed_count = {}

    for roi in unique_rois:
        rm = (sample_ids == roi) & tumor_mask
        typed = rm & ~np.isin(cell_types, list(LQ_TYPES))
        n_typed = np.sum(typed)
        if n_typed < MIN_CELLS:
            continue

        n_endo_roi = np.sum(is_endo & rm)
        roi_endo_frac[roi] = n_endo_roi / n_typed
        roi_endo_count[roi] = n_endo_roi
        roi_tma[roi] = tma_arr[rm][0]
        roi_typed_count[roi] = n_typed

    n_rois = len(roi_endo_frac)
    endo_fracs = np.array(list(roi_endo_frac.values()))
    print(f"ROIs passing filter: {n_rois}")
    print(f"Endothelial fraction: mean={np.mean(endo_fracs)*100:.2f}%, "
          f"median={np.median(endo_fracs)*100:.2f}%, "
          f"range=[{np.min(endo_fracs)*100:.2f}%, {np.max(endo_fracs)*100:.2f}%]")

    # Per-TMA breakdown
    tmas = sorted(set(roi_tma.values()))
    print(f"\n  {'TMA':>8} {'n_ROIs':>7} {'mean_endo%':>10} {'std':>8}")
    print("  " + "-" * 40)
    tma_endo_groups = {}
    for t in tmas:
        vals = [roi_endo_frac[r] * 100 for r in roi_endo_frac if roi_tma[r] == t]
        tma_endo_groups[t] = vals
        print(f"  {t:>8} {len(vals):>7} {np.mean(vals):>10.2f} {np.std(vals):>8.2f}")

    # KW test across TMAs
    kw_groups = [tma_endo_groups[t] for t in tmas if len(tma_endo_groups[t]) >= 3]
    if len(kw_groups) >= 2:
        H_kw, p_kw = kruskal(*kw_groups)
        print(f"\n  Kruskal-Wallis (endo% across TMAs): H={H_kw:.2f}, p={p_kw:.4f}")
    else:
        p_kw = 1.0

    # ---------------------------------------------------------------------------
    # 2. Immune cell distance to nearest vessel (KDTree)
    # ---------------------------------------------------------------------------
    print(f"\n--- Immune Cell Distance to Nearest Vessel ---")

    # Per-ROI: build KDTree of endothelial cells, query for each immune type
    immune_type_distances = {ct: [] for ct in IMMUNE_TYPES}  # cell-level distances
    roi_immune_dist = {ct: {} for ct in IMMUNE_TYPES}         # per-ROI mean distances

    filtered_rois = sorted(roi_endo_frac.keys())
    n_skip = 0
    for roi in filtered_rois:
        rm = (sample_ids == roi) & tumor_mask
        endo_roi = is_endo & rm
        n_endo_r = np.sum(endo_roi)
        if n_endo_r < MIN_ENDO:
            n_skip += 1
            continue

        # Build KDTree from endothelial coordinates
        endo_xy = np.column_stack([cx[endo_roi], cy[endo_roi]])
        tree = KDTree(endo_xy)

        # Query each immune type
        for ct in IMMUNE_TYPES:
            ct_mask = (cell_types == ct) & rm
            n_ct = np.sum(ct_mask)
            if n_ct < 3:
                continue
            ct_xy = np.column_stack([cx[ct_mask], cy[ct_mask]])
            dists, _ = tree.query(ct_xy, k=1)
            immune_type_distances[ct].extend(dists.tolist())
            roi_immune_dist[ct][roi] = float(np.mean(dists))

    print(f"ROIs skipped (<{MIN_ENDO} endothelial): {n_skip}")

    # Summary of distances
    print(f"\n  {'Cell Type':>25} {'n_cells':>10} {'mean_dist':>10} {'median':>10} {'n_ROIs':>8}")
    print("  " + "-" * 68)
    ct_mean_dists = {}
    ct_median_dists = {}
    ct_se_dists = {}
    for ct in IMMUNE_TYPES:
        d = np.array(immune_type_distances[ct])
        if len(d) < 10:
            print(f"  {ct:>25} {'too few':>10}")
            continue
        ct_mean_dists[ct] = np.mean(d)
        ct_median_dists[ct] = np.median(d)
        ct_se_dists[ct] = np.std(d) / np.sqrt(len(d))
        n_rois_ct = len(roi_immune_dist[ct])
        print(f"  {ct:>25} {len(d):>10,} {np.mean(d):>10.1f} {np.median(d):>10.1f} {n_rois_ct:>8}")

    # Statistical comparison: which cell types are closest?
    # Mann-Whitney U pairwise between top pairs
    sorted_cts = sorted(ct_mean_dists.keys(), key=lambda x: ct_mean_dists[x])
    print(f"\n  Ranked by mean distance to vessel (closest first):")
    for i, ct in enumerate(sorted_cts):
        print(f"    {i+1}. {ct}: {ct_mean_dists[ct]:.1f} px (median={ct_median_dists[ct]:.1f})")

    # Test: closest vs furthest
    if len(sorted_cts) >= 2:
        closest = sorted_cts[0]
        furthest = sorted_cts[-1]
        d_close = np.array(immune_type_distances[closest])
        d_far = np.array(immune_type_distances[furthest])
        U, p_mw = mannwhitneyu(d_close, d_far, alternative='less')
        print(f"\n  {closest} vs {furthest}: U={U:.0f}, p={p_mw:.2e}")

    # ---------------------------------------------------------------------------
    # 3. Endothelial fraction vs immune cell type fractions (per-ROI correlations)
    # ---------------------------------------------------------------------------
    print(f"\n--- Endothelial Fraction vs Immune Correlations ---")

    roi_fracs = compute_roi_celltype_fractions(sample_ids, cell_types, tumor_mask, LQ_TYPES)
    drivers = correlate_celltype_with_metric(roi_fracs, roi_endo_frac)

    print(f"Drivers of endothelial fraction (Spearman rho):")
    for ct_name, rho, p in drivers[:15]:
        print(f"  {ct_name:40s}  rho={rho:+.3f}  p={p:.2e}")

    # Identify strongest immune correlate for panel (b)
    best_immune_ct = None
    best_immune_rho = 0
    best_immune_p = 1.0
    immune_like = {'CD4 T cells', 'CD8 T cells', 'Macrophages', 'M1 Macrophages',
                   'M2 Macrophages', 'Dendritic cells', 'Myeloid (S100A9+)'}
    for ct_name, rho, p in drivers:
        if ct_name in immune_like and abs(rho) > abs(best_immune_rho):
            best_immune_ct = ct_name
            best_immune_rho = rho
            best_immune_p = p

    print(f"\n  Strongest immune correlate: {best_immune_ct} (rho={best_immune_rho:+.3f}, p={best_immune_p:.2e})")

    # ---------------------------------------------------------------------------
    # 4. Endothelial density in follicular vs interfollicular domains
    # ---------------------------------------------------------------------------
    print(f"\n--- Endothelial Density: Follicular vs Interfollicular ---")

    roi_endo_foll = {}
    roi_endo_inter = {}
    for roi in filtered_rois:
        rm = (sample_ids == roi) & tumor_mask
        # Follicular
        foll_typed = rm & foll_mask & ~np.isin(cell_types, list(LQ_TYPES))
        n_foll = np.sum(foll_typed)
        n_endo_foll = np.sum(is_endo & rm & foll_mask)
        # Interfollicular
        inter_typed = rm & inter_mask & ~np.isin(cell_types, list(LQ_TYPES))
        n_inter = np.sum(inter_typed)
        n_endo_inter = np.sum(is_endo & rm & inter_mask)

        if n_foll >= 100:
            roi_endo_foll[roi] = n_endo_foll / n_foll
        if n_inter >= 100:
            roi_endo_inter[roi] = n_endo_inter / n_inter

    common_domain_rois = sorted(set(roi_endo_foll.keys()) & set(roi_endo_inter.keys()))
    if len(common_domain_rois) >= 5:
        foll_vals = np.array([roi_endo_foll[r] * 100 for r in common_domain_rois])
        inter_vals = np.array([roi_endo_inter[r] * 100 for r in common_domain_rois])
        U_dom, p_dom = mannwhitneyu(inter_vals, foll_vals, alternative='greater')
        print(f"  Follicular: mean={np.mean(foll_vals):.2f}%, median={np.median(foll_vals):.2f}%")
        print(f"  Interfollicular: mean={np.mean(inter_vals):.2f}%, median={np.median(inter_vals):.2f}%")
        print(f"  Mann-Whitney (inter > foll): U={U_dom:.0f}, p={p_dom:.2e}")
        print(f"  Ratio: {np.mean(inter_vals)/np.mean(foll_vals):.2f}x")
    else:
        p_dom = 1.0
        foll_vals = np.array([])
        inter_vals = np.array([])
        print("  Too few ROIs with both domain types")

    # ---------------------------------------------------------------------------
    # 5. Leave-one-TMA-out sensitivity
    # ---------------------------------------------------------------------------
    print(f"\n--- Leave-One-TMA-Out Sensitivity ---")

    loo_results = []
    for excl in tmas:
        rois_keep = [r for r in filtered_rois if roi_tma[r] != excl]
        if len(rois_keep) < 5:
            continue

        # Recompute domain test
        common_k = [r for r in rois_keep if r in roi_endo_foll and r in roi_endo_inter]
        if len(common_k) >= 5:
            fv = np.array([roi_endo_foll[r] * 100 for r in common_k])
            iv = np.array([roi_endo_inter[r] * 100 for r in common_k])
            _, p_loo_dom = mannwhitneyu(iv, fv, alternative='greater')
        else:
            p_loo_dom = 1.0

        # Recompute best immune correlate
        ef_k = {r: roi_endo_frac[r] for r in rois_keep}
        fracs_k = {r: roi_fracs[r] for r in rois_keep if r in roi_fracs}
        drv_k = correlate_celltype_with_metric(fracs_k, ef_k)
        # Find Macrophage/strongest immune
        best_rho_k = 0.0
        p_rho_k = 1.0
        for ct_name, rho_k, p_k in drv_k:
            if ct_name == best_immune_ct:
                best_rho_k = rho_k
                p_rho_k = p_k
                break

        print(f"  Excl {excl} (n={len(rois_keep)}): domain p={p_loo_dom:.2e}, "
              f"{best_immune_ct} rho={best_rho_k:+.3f} p={p_rho_k:.2e}")
        loo_results.append((excl, p_loo_dom, best_rho_k, p_rho_k))

    # ---------------------------------------------------------------------------
    # 6. Generate cartoon
    # ---------------------------------------------------------------------------
    cartoon_path = generate_cartoon()

    # ===================================================================
    # MAIN FIGURE: 2 rows x 3 cols
    # ===================================================================
    print(f"\n--- Generating Main Figure ---")
    fig, axes = plt.subplots(2, 3, figsize=(16, 10))

    # (a) Concept cartoon
    add_cartoon(axes[0, 0], cartoon_path)
    label_panel(axes[0, 0], 'a')

    # (b) Per-ROI scatter: endothelial fraction vs strongest immune correlate
    ax = axes[0, 1]
    common_b = sorted(set(roi_endo_frac.keys()) & set(roi_fracs.keys()))
    if best_immune_ct:
        for roi in common_b:
            c = TMA_COLORS.get(roi_tma.get(roi, ''), '#999999')
            endo_pct = roi_endo_frac[roi] * 100
            immune_pct = roi_fracs[roi].get(best_immune_ct, 0) * 100
            ax.scatter(endo_pct, immune_pct, c=c, s=30,
                       alpha=0.6, edgecolors='white', linewidths=0.3)
        # Regression line
        x_arr = np.array([roi_endo_frac[r] * 100 for r in common_b])
        y_arr = np.array([roi_fracs[r].get(best_immune_ct, 0) * 100 for r in common_b])
        z = np.polyfit(x_arr, y_arr, 1)
        x_line = np.linspace(x_arr.min(), x_arr.max(), 100)
        ax.plot(x_line, np.polyval(z, x_line), 'k--', lw=1, alpha=0.5)
        ax.set_xlabel('Endothelial % of typed cells')
        ax.set_ylabel(f'{best_immune_ct} %')
        sig = '***' if best_immune_p < 0.001 else '**' if best_immune_p < 0.01 else '*' if best_immune_p < 0.05 else 'n.s.'
        ax.set_title(f'Endothelial vs {best_immune_ct}\n'
                     f'rho={best_immune_rho:+.3f}, p={best_immune_p:.2e} {sig}')
        tma_handles = [Line2D([0], [0], marker='o', color='w', markerfacecolor=c,
                              markersize=7, label=t) for t, c in TMA_COLORS.items()]
        ax.legend(handles=tma_handles, fontsize=7, loc='best')
    label_panel(ax, 'b')

    # (c) Bar chart: mean distance to nearest vessel by cell type
    ax = axes[0, 2]
    if sorted_cts:
        bar_cts = sorted_cts
        bar_means = [ct_mean_dists[ct] for ct in bar_cts]
        bar_ses = [ct_se_dists[ct] for ct in bar_cts]
        bar_colors = []
        immune_colors = {
            'CD4 T cells': '#4A90D9', 'CD8 T cells': '#2C5F8A',
            'Macrophages': '#27AE60', 'M1 Macrophages': '#16A085',
            'M2 Macrophages': '#1ABC9C', 'Dendritic cells': '#E67E22',
            'FDC': '#8E44AD', 'Myeloid (S100A9+)': '#D35400', 'pDC': '#F39C12'
        }
        for ct in bar_cts:
            bar_colors.append(immune_colors.get(ct, '#95A5A6'))

        y_pos = range(len(bar_cts))
        ax.barh(y_pos, bar_means, xerr=bar_ses, color=bar_colors, alpha=0.8,
                edgecolor='white', linewidth=0.5, capsize=2)
        ax.set_yticks(y_pos)
        ax.set_yticklabels([ct[:22] for ct in bar_cts], fontsize=7)
        ax.set_xlabel('Mean distance to nearest vessel (px)')
        ax.set_title('Immune Cell Proximity to Vessels\n(ranked closest→furthest)')
        ax.invert_yaxis()
    label_panel(ax, 'c')

    # (d) Representative spatial: low vs high vascular density
    ax = axes[1, 0]
    plot_representative_core_spatial(
        ax, cx, cy, sample_ids, cell_types, tumor_mask,
        roi_endo_frac, label_lo='Low vascular', label_hi='High vascular',
        metric_name='Endo%', top_n_types=10,
        domains=domains, foll_domains=foll_domains,
        highlight_mask=is_endo & tumor_mask,
        highlight_label='Endothelial',
        highlight_color='#FF4444', min_cells=MIN_CELLS,
        highlight_size=20, min_highlight_hi=5)
    label_panel(ax, 'd')

    # (e) Endothelial density: follicular vs interfollicular (box plot)
    ax = axes[1, 1]
    if len(foll_vals) > 0 and len(inter_vals) > 0:
        bp = ax.boxplot([foll_vals, inter_vals],
                        tick_labels=['Follicular', 'Interfollicular'],
                        patch_artist=True, widths=0.5)
        bp['boxes'][0].set_facecolor('#FFDDDD')
        bp['boxes'][0].set_edgecolor('#CC4444')
        bp['boxes'][1].set_facecolor('#DDDDFF')
        bp['boxes'][1].set_edgecolor('#4444CC')
        for median in bp['medians']:
            median.set_color('black')
            median.set_linewidth(2)

        # Overlay individual ROI points
        jitter_f = np.random.normal(1, 0.04, len(foll_vals))
        jitter_i = np.random.normal(2, 0.04, len(inter_vals))
        for roi_idx, roi in enumerate(common_domain_rois):
            c = TMA_COLORS.get(roi_tma.get(roi, ''), '#999999')
            ax.scatter(jitter_f[roi_idx], foll_vals[roi_idx], c=c, s=15,
                       alpha=0.5, edgecolors='white', linewidths=0.3, zorder=3)
            ax.scatter(jitter_i[roi_idx], inter_vals[roi_idx], c=c, s=15,
                       alpha=0.5, edgecolors='white', linewidths=0.3, zorder=3)

        ax.set_ylabel('Endothelial % of typed cells')
        sig_dom = '***' if p_dom < 0.001 else '**' if p_dom < 0.01 else '*' if p_dom < 0.05 else 'n.s.'
        ax.set_title(f'Endothelial Density by Domain\np={p_dom:.2e} {sig_dom}')

        # Significance bracket
        ymax = max(np.max(foll_vals), np.max(inter_vals))
        ax.plot([1, 1, 2, 2], [ymax*1.05, ymax*1.1, ymax*1.1, ymax*1.05], 'k-', lw=1)
        ax.text(1.5, ymax*1.12, sig_dom, ha='center', fontsize=11, fontweight='bold')
        ax.set_ylim(top=ymax * 1.25)
    else:
        ax.text(0.5, 0.5, 'Insufficient data', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'e')

    # (f) Driver analysis (cell type correlations with endothelial fraction)
    ax = axes[1, 2]
    top_n = min(12, len(drivers))
    if top_n > 0:
        top = drivers[:top_n]
        names = [d[0] for d in reversed(top)]
        rhos = [d[1] for d in reversed(top)]
        colors_bar = ['#e74c3c' if r < 0 else '#2ecc71' for r in rhos]
        ax.barh(range(len(names)), rhos, color=colors_bar, alpha=0.8)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=7)
        ax.set_xlabel('Spearman rho')
        ax.set_title('Endothelial Fraction Drivers\n(cell type rho with endo%)')
        ax.axvline(0, color='gray', lw=0.5)
    label_panel(ax, 'f')

    plt.suptitle('H4c: Perivascular Niche Mapping — S-panel\n'
                 '(pooled tumor cohort, all TMAs)',
                 fontsize=13, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    fig_path = os.path.join(OUTPUT_DIR, 'fig_h4c_S.png')
    plt.savefig(fig_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\nMain figure saved: {fig_path}")

    # ===================================================================
    # SUPPLEMENTARY FIGURE: Leave-one-TMA-out + per-TMA endothelial density
    # ===================================================================
    fig_s, axes_s = plt.subplots(1, 3, figsize=(15, 5))

    # (a) Per-TMA endothelial fraction boxplot
    ax = axes_s[0]
    box_data = [tma_endo_groups.get(t, []) for t in tmas]
    bp_s = ax.boxplot(box_data, tick_labels=tmas, patch_artist=True, widths=0.5)
    for patch, t in zip(bp_s['boxes'], tmas):
        patch.set_facecolor(TMA_COLORS.get(t, '#999'))
        patch.set_alpha(0.7)
    for median in bp_s['medians']:
        median.set_color('black')
        median.set_linewidth(2)
    ax.set_ylabel('Endothelial % of typed cells')
    ax.set_xlabel('TMA')
    ax.set_title(f'Endothelial Density per TMA\nKW p={p_kw:.4f}')
    label_panel(ax, 'a')

    # (b) Leave-one-out domain enrichment
    ax = axes_s[1]
    if loo_results:
        excl_names = [r[0] for r in loo_results]
        p_loo_vals = [r[1] for r in loo_results]
        colors_loo = [TMA_COLORS.get(t, '#999') for t in excl_names]
        ax.bar(excl_names, [-np.log10(max(p, 1e-300)) for p in p_loo_vals],
               color=colors_loo, alpha=0.7)
        ax.axhline(-np.log10(0.05), color='red', linestyle='--', lw=1,
                   label='p=0.05')
        ax.set_ylabel('-log10(p)')
        ax.set_xlabel('Excluded TMA')
        ax.set_title('LOO: Inter > Foll Domain Test')
        ax.legend(fontsize=8)
    label_panel(ax, 'b')

    # (c) Leave-one-out immune correlation
    ax = axes_s[2]
    if loo_results and best_immune_ct:
        excl_names = [r[0] for r in loo_results]
        rhos_loo = [r[2] for r in loo_results]
        colors_loo = [TMA_COLORS.get(t, '#999') for t in excl_names]
        ax.bar(excl_names, rhos_loo, color=colors_loo, alpha=0.7)
        ax.axhline(best_immune_rho, color='black', linestyle='--', lw=1,
                   label=f'Pooled rho={best_immune_rho:+.3f}')
        ax.set_ylabel(f'Spearman rho (endo% vs {best_immune_ct})')
        ax.set_xlabel('Excluded TMA')
        ax.set_title(f'LOO: Endo vs {best_immune_ct}')
        ax.legend(fontsize=8)
    label_panel(ax, 'c')

    plt.suptitle('H4c Supplementary: Leave-One-TMA-Out Sensitivity',
                 fontsize=12, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.90])
    fig_s_path = os.path.join(OUTPUT_DIR, 'fig_h4c_S_supp.png')
    plt.savefig(fig_s_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Supplementary figure saved: {fig_s_path}")

    # ---------------------------------------------------------------------------
    # Summary
    # ---------------------------------------------------------------------------
    print(f"\n{'='*70}")
    print(f"H4c SUMMARY")
    print(f"{'='*70}")
    print(f"Endothelial cells: {n_endo:,} in tumor ({np.mean(endo_fracs)*100:.2f}% mean)")
    print(f"ROIs analyzed: {n_rois}")

    if sorted_cts:
        print(f"\nClosest to vessels: {sorted_cts[0]} ({ct_mean_dists[sorted_cts[0]]:.1f} px)")
        print(f"Furthest from vessels: {sorted_cts[-1]} ({ct_mean_dists[sorted_cts[-1]]:.1f} px)")

    if len(foll_vals) > 0 and len(inter_vals) > 0:
        ratio = np.mean(inter_vals) / np.mean(foll_vals) if np.mean(foll_vals) > 0 else float('inf')
        print(f"\nDomain enrichment: interfollicular {ratio:.2f}x more endothelial (p={p_dom:.2e})")

    if best_immune_ct:
        print(f"Strongest immune correlate: {best_immune_ct} (rho={best_immune_rho:+.3f}, p={best_immune_p:.2e})")

    print(f"\nLeave-one-out stability: {'STABLE' if all(r[1] < 0.05 for r in loo_results) else 'VARIABLE'}")

    # Determine status
    confirmed_criteria = []
    if len(foll_vals) > 0 and p_dom < 0.05:
        confirmed_criteria.append('domain_enrichment')
    if best_immune_ct and best_immune_p < 0.05:
        confirmed_criteria.append('immune_correlation')
    if sorted_cts and len(sorted_cts) >= 2:
        confirmed_criteria.append('distance_hierarchy')

    if len(confirmed_criteria) >= 2:
        status = 'CONFIRMED'
    elif len(confirmed_criteria) == 1:
        status = 'PARTIALLY CONFIRMED'
    else:
        status = 'NOT CONFIRMED'

    print(f"\nSTATUS: {status}")
    print(f"  Criteria met: {confirmed_criteria}")
    print(f"{'='*70}")

    f.close()
    f_utag.close()

    return {
        'status': status,
        'n_endo': n_endo,
        'n_rois': n_rois,
        'mean_endo_frac': float(np.mean(endo_fracs)),
        'p_dom': p_dom,
        'best_immune_ct': best_immune_ct,
        'best_immune_rho': best_immune_rho,
        'best_immune_p': best_immune_p,
        'distance_ranking': sorted_cts if sorted_cts else [],
    }


if __name__ == '__main__':
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(CARTOON_DIR, exist_ok=True)
    results = run_h4c()
