#!/usr/bin/env python3
"""H6b: Spatial interaction diversity (co-occurrence entropy).

Tests whether the diversity of cell-cell spatial interactions (which types
neighbor which) adds independent information beyond phenotypic entropy
(cell type proportions alone).

Method:
  - For each ROI, build kNN graph (k=10) on cell centroids (scipy KDTree)
  - Record each cell's type and its k neighbors' types -> co-occurrence matrix
  - Normalize to probabilities, compute Shannon entropy on flattened distribution
  - Compare "interaction entropy" with "phenotypic entropy" (H6a)
  - Test whether interaction entropy adds independent spatial information

Analysis:
  1. Compute both entropies per ROI for both panels
  2. Scatter: interaction entropy vs phenotypic entropy — Spearman correlation
  3. Domain-level: interaction entropy in follicular vs interfollicular domains
  4. Cell type drivers of interaction entropy
  5. Leave-one-TMA-out sensitivity
  6. Residual analysis: does interaction entropy predict anything beyond phenotypic?

Output:
  - output/hypotheses_v8/fig_h6b_Both.png (main figure)
  - output/hypotheses_v8/fig_h6b_Both_supp.png (supplementary)
"""

import os, sys
import numpy as np
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from scipy.stats import spearmanr, mannwhitneyu, kruskal, pearsonr
from scipy.spatial import cKDTree
from collections import Counter

# Import helpers
sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from run_hypotheses_v2 import (
    load_array, is_tumor_core, get_tumor_mask,
    classify_domains, compute_roi_celltype_fractions, correlate_celltype_with_metric,
    add_cartoon, label_panel, plot_representative_core_spatial
)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
T_PANEL_PATH = 'output/all_TMA_T_global_v8.h5ad'
S_PANEL_PATH = 'output/all_TMA_S_global_v8.h5ad'
T_UTAG_PATH  = 'output/all_TMA_T_utag_ct_merged.h5ad'
S_UTAG_PATH  = 'output/all_TMA_S_utag_ct_merged.h5ad'

OUTPUT_DIR  = 'output/hypotheses_v8'
CARTOON_DIR = 'output/hypothesis_cartoons'
CARTOON_PATH = os.path.join(CARTOON_DIR, 'h6b_interaction_entropy.png')

TMA_COLORS = {'A1': '#3498db', 'B1': '#e74c3c', 'C1': '#2ecc71', 'Biomax': '#f39c12'}
LQ_TYPES = {'Low quality / Unassigned'}

# Min typed cells for ROI inclusion
MIN_CELLS_INHOUSE = 8000
MIN_CELLS_BIOMAX  = 5000

K_NEIGHBORS = 10  # kNN parameter

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(CARTOON_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# Generate concept cartoon
# ---------------------------------------------------------------------------
def generate_cartoon():
    if os.path.exists(CARTOON_PATH):
        print(f"Cartoon already exists: {CARTOON_PATH}")
        return

    print("Generating concept cartoon via Gemini...")
    try:
        from google import genai
        from google.genai import types
        from PIL import Image as PILImage
        import io

        client = genai.Client(api_key=os.environ['GEMINI_API_KEY'])

        prompt = (
            "Scientific concept illustration for a research paper. "
            "Show two panels side by side. "
            "LEFT panel labeled 'Phenotypic Entropy': a pie chart showing cell type proportions "
            "(B cells blue, T cells green, Macrophages red, etc.) with 'H_pheno' label. "
            "RIGHT panel labeled 'Interaction Entropy': a tissue cross-section showing cells as "
            "colored dots with lines between neighboring cells of different types, plus a small "
            "co-occurrence matrix (heatmap grid) labeled 'Cell-cell adjacency' and 'H_interact'. "
            "A central arrow between panels labeled 'Adds spatial information?'. "
            "Clean schematic style, white background, suitable for biology journal. "
            "No watermarks."
        )

        response = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(number_of_images=1)
        )
        if response.generated_images:
            img_bytes = response.generated_images[0].image.image_bytes
            img = PILImage.open(io.BytesIO(img_bytes))
            img.save(CARTOON_PATH, format='PNG')
            print(f"Cartoon saved: {CARTOON_PATH}")
        else:
            print("WARNING: No images generated by Gemini")
    except Exception as e:
        print(f"WARNING: Cartoon generation failed: {e}")


# ---------------------------------------------------------------------------
# Phenotypic entropy (Shannon on cell type proportions)
# ---------------------------------------------------------------------------
def compute_phenotypic_entropy(cell_types_roi):
    """Shannon entropy on cell type proportions, excluding LQ types."""
    clean = cell_types_roi[~np.isin(cell_types_roi, list(LQ_TYPES))]
    if len(clean) < 20:
        return np.nan
    counts = Counter(clean)
    total = sum(counts.values())
    props = np.array([c / total for c in counts.values()])
    props = props[props > 0]
    return -np.sum(props * np.log2(props))


# ---------------------------------------------------------------------------
# Interaction entropy (Shannon on kNN co-occurrence matrix)
# ---------------------------------------------------------------------------
def compute_interaction_entropy(cx_roi, cy_roi, cell_types_roi, k=K_NEIGHBORS):
    """Compute co-occurrence entropy from kNN graph on cell centroids.

    1. Build kNN graph (k neighbors) on cell coordinates
    2. For each cell, record (cell_type, neighbor_type) pairs
    3. Build co-occurrence matrix, normalize to probabilities
    4. Shannon entropy on flattened probability distribution

    Excludes LQ/Unassigned cells from both the graph and the counts.
    """
    # Filter to typed cells only
    typed_mask = ~np.isin(cell_types_roi, list(LQ_TYPES))
    if np.sum(typed_mask) < 50:
        return np.nan, None

    x = cx_roi[typed_mask]
    y = cy_roi[typed_mask]
    ct = cell_types_roi[typed_mask]

    # Get unique types in this ROI
    unique_types = sorted(set(ct))
    type_to_idx = {t: i for i, t in enumerate(unique_types)}
    n_types = len(unique_types)

    if n_types < 2:
        return np.nan, None

    # Build KDTree
    coords = np.column_stack([x, y])
    tree = cKDTree(coords)

    # Query k+1 neighbors (includes self)
    k_query = min(k + 1, len(coords))
    _, indices = tree.query(coords, k=k_query)

    # Build co-occurrence matrix
    cooc = np.zeros((n_types, n_types), dtype=np.float64)
    ct_idx = np.array([type_to_idx[c] for c in ct])

    for i in range(len(coords)):
        ci = ct_idx[i]
        for j_pos in range(1, k_query):  # skip self (position 0)
            neighbor = indices[i, j_pos]
            cj = ct_idx[neighbor]
            cooc[ci, cj] += 1

    # Normalize to probabilities
    total = cooc.sum()
    if total < 1:
        return np.nan, None

    probs = cooc / total
    flat = probs.flatten()
    flat = flat[flat > 0]

    H = -np.sum(flat * np.log2(flat))
    return H, cooc


# ---------------------------------------------------------------------------
# Analyze one panel
# ---------------------------------------------------------------------------
def analyze_panel(panel, v8_path, utag_path):
    """Run H6b analysis for one panel. Returns dict of results."""
    print(f"\n{'='*70}")
    print(f"H6b: Co-occurrence Entropy — {panel}-panel")
    print(f"{'='*70}")

    # Load data
    print(f"\nLoading {panel}-panel v8 data...")
    f_v8 = h5py.File(v8_path, 'r')
    f_utag = h5py.File(utag_path, 'r')

    sample_ids = load_array(f_v8, 'sample_id')
    tma_arr = load_array(f_v8, 'tma')
    cell_types = load_array(f_v8, 'cell_type')
    tumor_mask = get_tumor_mask(sample_ids)
    cx = f_v8['obs']['centroid_x'][:]
    cy = f_v8['obs']['centroid_y'][:]

    n_total = len(sample_ids)
    n_tumor = np.sum(tumor_mask)
    print(f"  {n_total:,} total -> {n_tumor:,} tumor cells (controls excluded)")

    # Classify UTAG domains
    print(f"\nClassifying UTAG domains...")
    domains, foll_domains, inter_domains = classify_domains(f_utag, cell_types, panel)

    # --- Per-ROI entropy computation ---
    print(f"\nComputing per-ROI entropies (k={K_NEIGHBORS})...")
    unique_rois = sorted(set(sample_ids[tumor_mask]))

    roi_data = {}
    for i_roi, roi in enumerate(unique_rois):
        rm = (sample_ids == roi) & tumor_mask
        ct_roi = cell_types[rm]
        tma_val = tma_arr[rm][0]

        # Count typed cells
        typed = ct_roi[~np.isin(ct_roi, list(LQ_TYPES))]
        n_typed = len(typed)

        # Min cell threshold
        min_cells = MIN_CELLS_BIOMAX if tma_val == 'Biomax' else MIN_CELLS_INHOUSE
        if n_typed < min_cells:
            continue

        # Phenotypic entropy
        H_pheno = compute_phenotypic_entropy(ct_roi)

        # Interaction entropy
        cx_roi = cx[rm]
        cy_roi = cy[rm]
        H_interact, cooc_matrix = compute_interaction_entropy(cx_roi, cy_roi, ct_roi, k=K_NEIGHBORS)

        if np.isnan(H_pheno) or np.isnan(H_interact):
            continue

        # Domain-level interaction entropy
        dom_roi = domains[rm]
        foll_cells = np.isin(dom_roi, foll_domains)
        inter_cells = np.isin(dom_roi, inter_domains)

        # Follicular interaction entropy
        n_foll = np.sum(foll_cells & ~np.isin(ct_roi, list(LQ_TYPES)))
        if n_foll >= 100:
            H_inter_foll, _ = compute_interaction_entropy(
                cx_roi[foll_cells], cy_roi[foll_cells], ct_roi[foll_cells])
        else:
            H_inter_foll = np.nan

        # Interfollicular interaction entropy
        n_inter = np.sum(inter_cells & ~np.isin(ct_roi, list(LQ_TYPES)))
        if n_inter >= 100:
            H_inter_inter, _ = compute_interaction_entropy(
                cx_roi[inter_cells], cy_roi[inter_cells], ct_roi[inter_cells])
        else:
            H_inter_inter = np.nan

        roi_data[roi] = {
            'tma': tma_val,
            'n_typed': n_typed,
            'H_pheno': H_pheno,
            'H_interact': H_interact,
            'H_inter_foll': H_inter_foll,
            'H_inter_inter': H_inter_inter,
        }

        if (i_roi + 1) % 20 == 0:
            print(f"  Processed {i_roi+1}/{len(unique_rois)} ROIs...")

    print(f"\n  ROIs passing filters: {len(roi_data)}")

    # --- Summary statistics ---
    rois = sorted(roi_data.keys())
    H_phenos = np.array([roi_data[r]['H_pheno'] for r in rois])
    H_interacts = np.array([roi_data[r]['H_interact'] for r in rois])
    tma_vals = np.array([roi_data[r]['tma'] for r in rois])

    print(f"\nPhenotypic entropy:")
    print(f"  Mean: {np.mean(H_phenos):.3f}, Std: {np.std(H_phenos):.3f}, "
          f"Range: [{np.min(H_phenos):.3f}, {np.max(H_phenos):.3f}]")
    print(f"\nInteraction entropy:")
    print(f"  Mean: {np.mean(H_interacts):.3f}, Std: {np.std(H_interacts):.3f}, "
          f"Range: [{np.min(H_interacts):.3f}, {np.max(H_interacts):.3f}]")

    # --- Correlation: interaction vs phenotypic entropy ---
    rho_main, p_main = spearmanr(H_phenos, H_interacts)
    r_pearson, p_pearson = pearsonr(H_phenos, H_interacts)
    print(f"\nInteraction entropy vs Phenotypic entropy:")
    print(f"  Spearman rho={rho_main:.3f}, p={p_main:.2e}")
    print(f"  Pearson  r={r_pearson:.3f}, p={p_pearson:.2e}")

    # --- Residual analysis: partial out phenotypic entropy ---
    # Regress H_interact ~ H_pheno, take residuals
    z = np.polyfit(H_phenos, H_interacts, 1)
    H_interact_predicted = np.polyval(z, H_phenos)
    residuals = H_interacts - H_interact_predicted
    residual_std = np.std(residuals)
    residual_range = np.max(residuals) - np.min(residuals)
    print(f"\nResidual analysis (H_interact | H_pheno):")
    print(f"  Residual std: {residual_std:.4f}")
    print(f"  Residual range: {residual_range:.4f}")
    print(f"  Coefficient of determination R^2: {r_pearson**2:.3f}")
    print(f"  Unexplained variance: {1 - r_pearson**2:.3f}")

    # What drives the residuals? Cell type fractions that correlate with
    # interaction entropy AFTER controlling for phenotypic entropy
    roi_residual = {r: res for r, res in zip(rois, residuals)}

    # --- Domain-level interaction entropy ---
    H_inter_folls = np.array([roi_data[r]['H_inter_foll'] for r in rois])
    H_inter_inters = np.array([roi_data[r]['H_inter_inter'] for r in rois])

    valid_domain = ~np.isnan(H_inter_folls) & ~np.isnan(H_inter_inters)
    n_domain = np.sum(valid_domain)
    print(f"\nDomain-level interaction entropy ({n_domain} ROIs with both domains):")

    if n_domain >= 10:
        foll_vals = H_inter_folls[valid_domain]
        inter_vals = H_inter_inters[valid_domain]
        u_stat, p_domain = mannwhitneyu(foll_vals, inter_vals, alternative='two-sided')
        print(f"  Follicular: mean={np.mean(foll_vals):.3f}, std={np.std(foll_vals):.3f}")
        print(f"  Interfollicular: mean={np.mean(inter_vals):.3f}, std={np.std(inter_vals):.3f}")
        print(f"  Mann-Whitney U: p={p_domain:.2e}")
        diff_pct = (np.mean(inter_vals) - np.mean(foll_vals)) / np.mean(foll_vals) * 100
        print(f"  Interfollicular {'higher' if diff_pct > 0 else 'lower'} by {abs(diff_pct):.1f}%")
    else:
        p_domain = np.nan
        print("  Insufficient ROIs with both domains")

    # --- Cell type drivers of interaction entropy ---
    print(f"\nCell type drivers of interaction entropy:")
    roi_fracs = compute_roi_celltype_fractions(sample_ids, cell_types, tumor_mask, LQ_TYPES)
    roi_interact_metric = {r: roi_data[r]['H_interact'] for r in rois}
    drivers_interact = correlate_celltype_with_metric(roi_fracs, roi_interact_metric)

    for ct_name, rho, p_d in drivers_interact[:12]:
        print(f"  {ct_name:40s}  rho={rho:+.3f}  p={p_d:.2e}")

    # Drivers of RESIDUAL interaction entropy (spatial information beyond composition)
    print(f"\nDrivers of RESIDUAL interaction entropy (independent of phenotypic):")
    drivers_residual = correlate_celltype_with_metric(roi_fracs, roi_residual)
    for ct_name, rho, p_d in drivers_residual[:12]:
        print(f"  {ct_name:40s}  rho={rho:+.3f}  p={p_d:.2e}")

    # --- Per-TMA breakdown ---
    tmas = sorted(set(tma_vals))
    print(f"\nPer-TMA interaction entropy:")
    tma_groups = {}
    for t in tmas:
        mask_t = tma_vals == t
        vals_t = H_interacts[mask_t]
        tma_groups[t] = vals_t
        print(f"  {t:>8}: n={len(vals_t):>3}, mean={np.mean(vals_t):.3f}, "
              f"std={np.std(vals_t):.3f}")

    # Kruskal-Wallis across TMAs
    kw_groups = [tma_groups[t] for t in tmas if len(tma_groups[t]) > 0]
    if len(kw_groups) >= 2:
        H_kw, p_kw = kruskal(*kw_groups)
        print(f"  Kruskal-Wallis: H={H_kw:.2f}, p={p_kw:.4f}")
    else:
        p_kw = np.nan

    # --- Leave-one-TMA-out sensitivity ---
    print(f"\nLeave-one-TMA-out sensitivity:")
    loo_results = []
    for exclude in tmas:
        keep = tma_vals != exclude
        if np.sum(keep) < 10:
            loo_results.append((exclude, np.nan, np.nan))
            continue
        rho_loo, p_loo = spearmanr(H_phenos[keep], H_interacts[keep])
        # Also compute R^2 for residual analysis
        r_loo, _ = pearsonr(H_phenos[keep], H_interacts[keep])
        loo_results.append((exclude, rho_loo, 1 - r_loo**2))
        print(f"  Excl {exclude}: Spearman rho={rho_loo:.3f}, p={p_loo:.2e}, "
              f"unexplained var={1 - r_loo**2:.3f}")

    # Keep arrays for figure generation before closing files
    result = {
        'panel': panel,
        'rois': rois,
        'roi_data': roi_data,
        'H_phenos': H_phenos,
        'H_interacts': H_interacts,
        'tma_vals': tma_vals,
        'tmas': tmas,
        'tma_groups': tma_groups,
        'rho_main': rho_main,
        'p_main': p_main,
        'r_pearson': r_pearson,
        'residuals': residuals,
        'residual_std': residual_std,
        'roi_residual': roi_residual,
        'H_inter_folls': H_inter_folls,
        'H_inter_inters': H_inter_inters,
        'p_domain': p_domain,
        'drivers_interact': drivers_interact,
        'drivers_residual': drivers_residual,
        'loo_results': loo_results,
        'p_kw': p_kw,
        'sample_ids': sample_ids,
        'cell_types': cell_types,
        'tumor_mask': tumor_mask,
        'cx': cx,
        'cy': cy,
    }

    f_v8.close()
    f_utag.close()

    return result


# ---------------------------------------------------------------------------
# Main figure (2x3) — combined Both panels
# ---------------------------------------------------------------------------
def make_main_figure(results_T, results_S):
    """Generate main H6b figure with combined results from both panels."""
    print("\n--- Generating main figure ---")
    fig, axes = plt.subplots(2, 3, figsize=(18, 11))

    # (a) Concept cartoon
    add_cartoon(axes[0, 0], CARTOON_PATH)
    label_panel(axes[0, 0], 'a')

    # (b) Scatter: interaction vs phenotypic entropy (both panels)
    ax = axes[0, 1]
    for res, marker, panel_label in [(results_T, 'o', 'T'), (results_S, 's', 'S')]:
        for t in res['tmas']:
            mask_t = res['tma_vals'] == t
            ax.scatter(res['H_phenos'][mask_t], res['H_interacts'][mask_t],
                       c=TMA_COLORS.get(t, 'gray'), alpha=0.5, s=20,
                       marker=marker, edgecolors='white', linewidths=0.3,
                       label=f'{t} ({panel_label})')
    # Regression lines
    for res, color, ls in [(results_T, '#2c3e50', '-'), (results_S, '#8e44ad', '--')]:
        z = np.polyfit(res['H_phenos'], res['H_interacts'], 1)
        x_line = np.linspace(np.min(res['H_phenos']), np.max(res['H_phenos']), 50)
        ax.plot(x_line, np.polyval(z, x_line), color=color, linestyle=ls, lw=1.5,
                alpha=0.7, label=f'{res["panel"]}: rho={res["rho_main"]:.3f}')

    ax.set_xlabel('Phenotypic Entropy (bits)', fontsize=10)
    ax.set_ylabel('Interaction Entropy (bits)', fontsize=10)
    p_T = results_T['p_main']
    p_S = results_S['p_main']
    ax.set_title(f'Interaction vs Phenotypic Entropy\n'
                 f'T: rho={results_T["rho_main"]:.3f}, p={p_T:.1e}\n'
                 f'S: rho={results_S["rho_main"]:.3f}, p={p_S:.1e}',
                 fontsize=9)
    ax.legend(fontsize=5.5, loc='upper left', ncol=2)
    label_panel(ax, 'b')

    # (c) Domain-level interaction entropy (follicular vs interfollicular)
    ax = axes[0, 2]
    box_data = []
    box_labels = []
    box_colors = []

    for res in [results_T, results_S]:
        panel = res['panel']
        valid = ~np.isnan(res['H_inter_folls']) & ~np.isnan(res['H_inter_inters'])
        if np.sum(valid) >= 5:
            foll_v = res['H_inter_folls'][valid]
            inter_v = res['H_inter_inters'][valid]
            box_data.extend([foll_v, inter_v])
            box_labels.extend([f'{panel}\nFollicular\n(n={len(foll_v)})',
                               f'{panel}\nInterfoll.\n(n={len(inter_v)})'])
            box_colors.extend(['#FFDDDD', '#DDDDFF'])

    if len(box_data) > 0:
        bp = ax.boxplot(box_data, tick_labels=box_labels, patch_artist=True, widths=0.5)
        for patch, c in zip(bp['boxes'], box_colors):
            patch.set_facecolor(c)
            patch.set_alpha(0.8)
        # Add jittered points
        for i, data in enumerate(box_data):
            jitter = np.random.RandomState(42 + i).normal(0, 0.04, len(data))
            ax.scatter(np.ones(len(data)) * (i + 1) + jitter, data,
                       c='gray', alpha=0.3, s=8, edgecolors='none', zorder=5)

        # Significance annotations
        bracket_y = max(np.max(d) for d in box_data) * 1.02
        for panel_idx, res in enumerate([results_T, results_S]):
            if not np.isnan(res['p_domain']):
                x1 = panel_idx * 2 + 1
                x2 = panel_idx * 2 + 2
                y_br = bracket_y + panel_idx * bracket_y * 0.08
                ax.plot([x1, x1, x2, x2], [y_br, y_br * 1.02, y_br * 1.02, y_br],
                        'k-', lw=0.8)
                p_str = f'p={res["p_domain"]:.1e}' if res['p_domain'] < 0.001 else f'p={res["p_domain"]:.3f}'
                ax.text((x1 + x2) / 2, y_br * 1.03, p_str, ha='center', fontsize=7)

    ax.set_ylabel('Interaction Entropy (bits)', fontsize=10)
    ax.set_title('Interaction Entropy by Domain', fontsize=10)
    ax.tick_params(axis='x', labelsize=7)
    label_panel(ax, 'c')

    # (d) Representative cores (T-panel, low vs high interaction entropy)
    ax = axes[1, 0]
    res = results_T
    roi_metric = {r: res['roi_data'][r]['H_interact'] for r in res['rois']}
    plot_representative_core_spatial(
        ax, res['cx'], res['cy'], res['sample_ids'], res['cell_types'],
        res['tumor_mask'], roi_metric,
        label_lo='Low H_interact', label_hi='High H_interact',
        metric_name='H_int', top_n_types=10,
        min_cells=MIN_CELLS_INHOUSE
    )
    ax.set_title('Representative Cores (T-panel)', fontsize=10)
    label_panel(ax, 'd')

    # (e) Residual analysis — histograms of residuals for both panels
    ax = axes[1, 1]
    for res, color, panel_label in [(results_T, '#2c3e50', 'T'), (results_S, '#8e44ad', 'S')]:
        ax.hist(res['residuals'], bins=25, alpha=0.5, color=color,
                edgecolor='white', label=f'{panel_label} (std={res["residual_std"]:.3f})')
    ax.axvline(0, color='gray', linestyle='--', lw=1)
    ax.set_xlabel('Residual Interaction Entropy (bits)', fontsize=10)
    ax.set_ylabel('Number of ROIs', fontsize=10)
    R2_T = results_T['r_pearson'] ** 2
    R2_S = results_S['r_pearson'] ** 2
    ax.set_title(f'Residual H_interact | H_pheno\n'
                 f'T: R$^2$={R2_T:.3f}, unexpl.={1-R2_T:.3f}\n'
                 f'S: R$^2$={R2_S:.3f}, unexpl.={1-R2_S:.3f}', fontsize=9)
    ax.legend(fontsize=8)
    label_panel(ax, 'e')

    # (f) Drivers of RESIDUAL interaction entropy (T-panel)
    ax = axes[1, 2]
    drivers = results_T['drivers_residual']
    top_n = min(12, len(drivers))
    if top_n > 0:
        top = drivers[:top_n]
        names = [d[0] for d in reversed(top)]
        rhos = [d[1] for d in reversed(top)]
        colors_bar = ['#e74c3c' if r < 0 else '#2ecc71' for r in rhos]
        ax.barh(range(len(names)), rhos, color=colors_bar, alpha=0.8)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=7)
        ax.set_xlabel('Spearman rho', fontsize=10)
        ax.set_title('Residual Interaction Entropy Drivers\n(spatial info beyond composition, T)',
                      fontsize=9)
        ax.axvline(0, color='gray', lw=0.5)
    label_panel(ax, 'f')

    plt.suptitle('H6b: Spatial Interaction Diversity (Co-occurrence Entropy) — Both Panels',
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.94])
    main_path = os.path.join(OUTPUT_DIR, 'fig_h6b_Both.png')
    plt.savefig(main_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\nMain figure saved: {main_path}")
    return main_path


# ---------------------------------------------------------------------------
# Supplementary figure (2x3) — per-TMA, LOO, additional panels
# ---------------------------------------------------------------------------
def make_supp_figure(results_T, results_S):
    """Generate supplementary figure with per-TMA and sensitivity analyses."""
    print("\n--- Generating supplementary figure ---")
    fig, axes = plt.subplots(2, 3, figsize=(18, 11))

    # (a) Per-TMA interaction entropy boxplot (T-panel)
    ax = axes[0, 0]
    res = results_T
    tmas = res['tmas']
    box_data = [res['tma_groups'][t] for t in tmas]
    bp = ax.boxplot(box_data, tick_labels=tmas, patch_artist=True, widths=0.5)
    for patch, t in zip(bp['boxes'], tmas):
        patch.set_facecolor(TMA_COLORS.get(t, 'gray'))
        patch.set_alpha(0.6)
    # Add jittered points
    for i, data in enumerate(box_data):
        jitter = np.random.RandomState(42 + i).normal(0, 0.05, len(data))
        ax.scatter(np.ones(len(data)) * (i + 1) + jitter, data,
                   c='gray', alpha=0.3, s=8, edgecolors='none', zorder=5)
    ax.set_ylabel('Interaction Entropy (bits)', fontsize=10)
    ax.set_xlabel('TMA', fontsize=10)
    p_kw_str = f'p={res["p_kw"]:.4f}' if not np.isnan(res['p_kw']) else 'n/a'
    ax.set_title(f'Per-TMA Interaction Entropy (T)\nKruskal-Wallis {p_kw_str}', fontsize=10)
    label_panel(ax, 'a')

    # (b) Per-TMA interaction entropy boxplot (S-panel)
    ax = axes[0, 1]
    res = results_S
    tmas_s = res['tmas']
    box_data_s = [res['tma_groups'][t] for t in tmas_s]
    bp_s = ax.boxplot(box_data_s, tick_labels=tmas_s, patch_artist=True, widths=0.5)
    for patch, t in zip(bp_s['boxes'], tmas_s):
        patch.set_facecolor(TMA_COLORS.get(t, 'gray'))
        patch.set_alpha(0.6)
    for i, data in enumerate(box_data_s):
        jitter = np.random.RandomState(42 + i).normal(0, 0.05, len(data))
        ax.scatter(np.ones(len(data)) * (i + 1) + jitter, data,
                   c='gray', alpha=0.3, s=8, edgecolors='none', zorder=5)
    ax.set_ylabel('Interaction Entropy (bits)', fontsize=10)
    ax.set_xlabel('TMA', fontsize=10)
    p_kw_str_s = f'p={res["p_kw"]:.4f}' if not np.isnan(res['p_kw']) else 'n/a'
    ax.set_title(f'Per-TMA Interaction Entropy (S)\nKruskal-Wallis {p_kw_str_s}', fontsize=10)
    label_panel(ax, 'b')

    # (c) Leave-one-TMA-out sensitivity (rho values)
    ax = axes[0, 2]
    all_tmas = sorted(set(results_T['tmas']) | set(results_S['tmas']))
    x_pos = np.arange(len(all_tmas))
    w = 0.35

    loo_T = {r[0]: r[1] for r in results_T['loo_results']}
    loo_S = {r[0]: r[1] for r in results_S['loo_results']}

    rhos_T = [loo_T.get(t, np.nan) for t in all_tmas]
    rhos_S = [loo_S.get(t, np.nan) for t in all_tmas]

    ax.bar(x_pos - w/2, rhos_T, width=w, color='#2c3e50', alpha=0.7, label='T-panel')
    ax.bar(x_pos + w/2, rhos_S, width=w, color='#8e44ad', alpha=0.7, label='S-panel')

    # Reference lines for full-cohort rho
    ax.axhline(results_T['rho_main'], color='#2c3e50', linestyle='--', lw=0.8, alpha=0.5)
    ax.axhline(results_S['rho_main'], color='#8e44ad', linestyle='--', lw=0.8, alpha=0.5)

    ax.set_xticks(x_pos)
    ax.set_xticklabels([f'Excl\n{t}' for t in all_tmas], fontsize=8)
    ax.set_ylabel('Spearman rho\n(H_interact vs H_pheno)', fontsize=10)
    ax.set_title('LOO Sensitivity', fontsize=10)
    ax.legend(fontsize=8)
    ax.axhline(0, color='gray', lw=0.5)
    label_panel(ax, 'c')

    # (d) Drivers of interaction entropy (S-panel)
    ax = axes[1, 0]
    drivers = results_S['drivers_interact']
    top_n = min(12, len(drivers))
    if top_n > 0:
        top = drivers[:top_n]
        names = [d[0] for d in reversed(top)]
        rhos = [d[1] for d in reversed(top)]
        colors_bar = ['#e74c3c' if r < 0 else '#2ecc71' for r in rhos]
        ax.barh(range(len(names)), rhos, color=colors_bar, alpha=0.8)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=7)
        ax.set_xlabel('Spearman rho', fontsize=10)
        ax.set_title('Interaction Entropy Drivers (S)', fontsize=9)
        ax.axvline(0, color='gray', lw=0.5)
    label_panel(ax, 'd')

    # (e) Drivers of RESIDUAL interaction entropy (S-panel)
    ax = axes[1, 1]
    drivers_res = results_S['drivers_residual']
    top_n = min(12, len(drivers_res))
    if top_n > 0:
        top = drivers_res[:top_n]
        names = [d[0] for d in reversed(top)]
        rhos = [d[1] for d in reversed(top)]
        colors_bar = ['#e74c3c' if r < 0 else '#2ecc71' for r in rhos]
        ax.barh(range(len(names)), rhos, color=colors_bar, alpha=0.8)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=7)
        ax.set_xlabel('Spearman rho', fontsize=10)
        ax.set_title('Residual Interact. Entropy Drivers (S)', fontsize=9)
        ax.axvline(0, color='gray', lw=0.5)
    label_panel(ax, 'e')

    # (f) R^2 decomposition: bar chart showing explained vs unexplained variance
    ax = axes[1, 2]
    R2_T = results_T['r_pearson'] ** 2
    R2_S = results_S['r_pearson'] ** 2
    panels_bar = ['T-panel', 'S-panel']
    explained = [R2_T, R2_S]
    unexplained = [1 - R2_T, 1 - R2_S]

    x_bar = np.arange(2)
    ax.bar(x_bar, explained, width=0.5, color='#3498db', alpha=0.7,
           label='Explained by H_pheno')
    ax.bar(x_bar, unexplained, width=0.5, bottom=explained, color='#e74c3c',
           alpha=0.7, label='Independent spatial info')
    ax.set_xticks(x_bar)
    ax.set_xticklabels(panels_bar, fontsize=10)
    ax.set_ylabel('Fraction of Variance', fontsize=10)
    ax.set_title('Variance Decomposition\nof Interaction Entropy', fontsize=10)
    ax.legend(fontsize=8, loc='center right')
    ax.set_ylim(0, 1.15)

    # Add percentage labels
    for i in range(2):
        ax.text(i, explained[i] / 2, f'{explained[i]*100:.1f}%',
                ha='center', va='center', fontsize=10, fontweight='bold', color='white')
        ax.text(i, explained[i] + unexplained[i] / 2, f'{unexplained[i]*100:.1f}%',
                ha='center', va='center', fontsize=10, fontweight='bold', color='white')

    label_panel(ax, 'f')

    plt.suptitle('H6b: Co-occurrence Entropy — Supplementary (Per-TMA & Sensitivity)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.94])
    supp_path = os.path.join(OUTPUT_DIR, 'fig_h6b_Both_supp.png')
    plt.savefig(supp_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Supplementary figure saved: {supp_path}")
    return supp_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def run_h6b():
    print("=" * 70)
    print("H6b: Spatial Interaction Diversity (Co-occurrence Entropy)")
    print("=" * 70)

    # Generate cartoon
    generate_cartoon()

    # Analyze both panels
    results_T = analyze_panel('T', T_PANEL_PATH, T_UTAG_PATH)
    results_S = analyze_panel('S', S_PANEL_PATH, S_UTAG_PATH)

    # Generate figures
    main_path = make_main_figure(results_T, results_S)
    supp_path = make_supp_figure(results_T, results_S)

    # --- Final summary ---
    print("\n" + "=" * 70)
    print("H6b SUMMARY")
    print("=" * 70)

    for res in [results_T, results_S]:
        panel = res['panel']
        R2 = res['r_pearson'] ** 2
        unexplained = 1 - R2
        print(f"\n{panel}-panel:")
        print(f"  Interaction vs Phenotypic entropy: "
              f"Spearman rho={res['rho_main']:.3f}, p={res['p_main']:.2e}")
        print(f"  Pearson R^2={R2:.3f}, unexplained variance={unexplained:.3f} ({unexplained*100:.1f}%)")
        print(f"  Residual std: {res['residual_std']:.4f} bits")
        if not np.isnan(res['p_domain']):
            print(f"  Domain-level: follicular vs interfollicular p={res['p_domain']:.2e}")
        print(f"  LOO stability: {all(not np.isnan(r[1]) and r[1] > 0.5 for r in res['loo_results'])}")

    # Determine hypothesis status
    # H6b asks: does interaction entropy add independent spatial information?
    # Key criteria:
    #   1. High but <1.0 correlation with phenotypic entropy (correlated but not redundant)
    #   2. Meaningful unexplained variance (>10%)
    #   3. Residual entropy driven by specific cell types (biologically interpretable)
    #   4. Domain differences in interaction entropy
    R2_T = results_T['r_pearson'] ** 2
    R2_S = results_S['r_pearson'] ** 2
    unexpl_T = 1 - R2_T
    unexpl_S = 1 - R2_S

    has_independent_info = (unexpl_T > 0.05 or unexpl_S > 0.05)
    has_domain_diff = (not np.isnan(results_T['p_domain']) and results_T['p_domain'] < 0.05) or \
                      (not np.isnan(results_S['p_domain']) and results_S['p_domain'] < 0.05)
    has_drivers = len(results_T['drivers_residual']) > 0 and \
                  abs(results_T['drivers_residual'][0][1]) > 0.1

    if has_independent_info and (has_domain_diff or has_drivers):
        status = "CONFIRMED"
        reason = (f"Co-occurrence entropy adds independent spatial information beyond phenotypic entropy. "
                  f"T: {unexpl_T*100:.1f}% unexplained variance; "
                  f"S: {unexpl_S*100:.1f}% unexplained variance.")
    elif has_independent_info:
        status = "CONFIRMED"
        reason = (f"Co-occurrence entropy captures spatial interaction diversity not fully explained "
                  f"by cell type proportions (T: {unexpl_T*100:.1f}%, S: {unexpl_S*100:.1f}% "
                  f"independent variance).")
    elif R2_T > 0.95 and R2_S > 0.95:
        status = "NOT CONFIRMED"
        reason = (f"Interaction entropy is nearly fully explained by phenotypic entropy "
                  f"(T: R^2={R2_T:.3f}, S: R^2={R2_S:.3f}). No independent spatial information.")
    else:
        status = "INCONCLUSIVE"
        reason = "Mixed results across panels."

    print(f"\nStatus: {status}")
    print(f"Reason: {reason}")
    print(f"\nFigures: {main_path}, {supp_path}")

    return status, reason


if __name__ == '__main__':
    run_h6b()
