#!/usr/bin/env python3
"""H1a: Follicle boundary sharpness correlates with disease biology.

Panel: S-panel
Rationale: FL is characterized by effaced follicular architecture.
Quantifying boundary sharpness could stratify tumors by degree of
architectural disruption.

Test: Quantify B cell density gradient at follicle boundaries;
correlate sharpness score with inter-ROI variability.
"""

import os, sys
import numpy as np
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from scipy.stats import spearmanr, mannwhitneyu
from scipy.spatial import KDTree
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from run_hypotheses_v2 import (
    load_array, get_marker_idx, load_marker, is_tumor_core, get_tumor_mask,
    classify_domains, compute_roi_celltype_fractions, correlate_celltype_with_metric,
    add_cartoon, label_panel, plot_representative_core_spatial,
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V8_PATH = os.path.join(BASE, 'output', 'all_TMA_S_global_v8.h5ad')
UTAG_PATH = os.path.join(BASE, 'output', 'all_TMA_S_utag_ct_merged.h5ad')
OUTPUT_DIR = os.path.join(BASE, 'output', 'hypotheses_v8')
CARTOON_DIR = os.path.join(BASE, 'output', 'hypothesis_cartoons')
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(CARTOON_DIR, exist_ok=True)

PANEL = 'S'
MIN_CELLS = 5000  # S-panel min typed cells
BOUNDARY_DIST = 30  # pixels: cells within this of domain boundary
BAND_WIDTH = 50     # pixels: band for inner/outer sharpness ratio
GRADIENT_INNER = 25 # pixels: inner band for CD20 gradient
GRADIENT_OUTER = 25 # pixels: outer band for CD20 gradient

TMA_COLORS = {'A1': '#3498db', 'B1': '#e74c3c', 'C1': '#2ecc71', 'Biomax': '#f39c12'}

LQ_TYPES = {'Low quality / Unassigned'}


# ---------------------------------------------------------------------------
# Generate concept cartoon
# ---------------------------------------------------------------------------
def generate_cartoon():
    cartoon_path = os.path.join(CARTOON_DIR, 'h1a_boundary_sharpness.png')
    if os.path.exists(cartoon_path):
        print(f"Cartoon already exists: {cartoon_path}")
        return cartoon_path

    print("Generating concept cartoon via Gemini...")
    try:
        from google import genai
        from google.genai import types
        from PIL import Image as PILImage
        import io

        client = genai.Client(api_key=os.environ['GEMINI_API_KEY'])

        prompt = (
            "Create a simple, clean scientific concept cartoon for a research figure. "
            "Show two panels side by side: LEFT labeled 'Sharp boundary' showing a "
            "well-defined circular follicle (pale pink/salmon circle) with a crisp edge, "
            "filled with densely packed blue dots (B cells), surrounded by orange dots "
            "(T cells) outside. The transition from blue to orange is abrupt at the boundary. "
            "RIGHT labeled 'Diffuse boundary' showing an irregularly shaped follicle "
            "(same pale pink but with fuzzy/irregular edges) where blue and orange dots "
            "are intermixed at the boundary, creating a gradient zone. "
            "Add a small arrow at each boundary zone: sharp one labeled 'steep gradient', "
            "diffuse one labeled 'gradual gradient'. "
            "Use a white background, minimal labels, publication-quality style. "
            "No text other than the labels mentioned. Simple, diagrammatic, not photographic."
        )

        response = client.models.generate_images(
            model='imagen-4.0-fast-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(number_of_images=1),
        )

        if response.generated_images:
            img_bytes = response.generated_images[0].image.image_bytes
            img = PILImage.open(io.BytesIO(img_bytes))
            # Save as jpg first, then convert to PNG
            jpg_path = cartoon_path.replace('.png', '.jpg')
            img.save(jpg_path, 'JPEG', quality=95)
            img_png = PILImage.open(jpg_path)
            img_png.save(cartoon_path, 'PNG')
            os.remove(jpg_path)
            print(f"Cartoon saved: {cartoon_path}")
        else:
            print("Warning: No image generated by Gemini")
    except Exception as e:
        print(f"Warning: Cartoon generation failed: {e}")

    return cartoon_path


# ---------------------------------------------------------------------------
# Boundary sharpness computation
# ---------------------------------------------------------------------------
def compute_boundary_sharpness(cx_roi, cy_roi, domains_roi, foll_domains,
                                b_cell_mask_roi, cd20_roi,
                                boundary_dist=BOUNDARY_DIST,
                                band_width=BAND_WIDTH,
                                gradient_inner=GRADIENT_INNER,
                                gradient_outer=GRADIENT_OUTER):
    """Compute boundary sharpness metrics for a single ROI.

    Returns dict with:
      - ratio_sharpness: B cell fraction inside foll / outside foll (within band)
      - gradient_sharpness: mean CD20 inner band - mean CD20 outer band
      - n_boundary_cells: number of cells near the boundary
      - b_frac_inner: B cell fraction inside follicular domains (within band)
      - b_frac_outer: B cell fraction outside follicular domains (within band)
    """
    is_foll = np.isin(domains_roi, foll_domains)
    n_foll = np.sum(is_foll)
    n_inter = np.sum(~is_foll)

    if n_foll < 20 or n_inter < 20:
        return None

    coords = np.column_stack([cx_roi, cy_roi])
    tree = KDTree(coords)

    # Find boundary cells: cells near the foll/inter interface
    # A cell is near the boundary if it is within boundary_dist of
    # at least one cell from the opposite domain
    foll_coords = coords[is_foll]
    inter_coords = coords[~is_foll]

    if len(foll_coords) == 0 or len(inter_coords) == 0:
        return None

    tree_foll = KDTree(foll_coords)
    tree_inter = KDTree(inter_coords)

    # For each follicular cell, distance to nearest interfollicular cell
    dist_foll_to_inter, _ = tree_inter.query(foll_coords, k=1)
    # For each interfollicular cell, distance to nearest follicular cell
    dist_inter_to_foll, _ = tree_foll.query(inter_coords, k=1)

    # Inner band: follicular cells within band_width of the boundary
    inner_band = is_foll.copy()
    inner_band[is_foll] &= (dist_foll_to_inter <= band_width)

    # Outer band: interfollicular cells within band_width of the boundary
    outer_band = (~is_foll).copy()
    outer_band[~is_foll] &= (dist_inter_to_foll <= band_width)

    n_inner = np.sum(inner_band)
    n_outer = np.sum(outer_band)

    if n_inner < 10 or n_outer < 10:
        return None

    # B cell fraction in inner vs outer band
    b_frac_inner = np.sum(b_cell_mask_roi[inner_band]) / n_inner
    b_frac_outer = np.sum(b_cell_mask_roi[outer_band]) / n_outer

    # Require minimum B cells in inner band (at least 5% to be a real follicle)
    if b_frac_inner < 0.05:
        return None

    # Ratio sharpness: B frac inside / B frac outside
    # Higher = sharper (B cells more confined to follicle)
    if b_frac_outer > 0.01:
        ratio_sharpness = b_frac_inner / b_frac_outer
    else:
        ratio_sharpness = b_frac_inner / 0.01  # avoid div by zero

    # Gradient sharpness: difference in mean CD20 intensity
    # Inner gradient band (0-gradient_inner px inside foll boundary)
    inner_gradient = is_foll.copy()
    inner_gradient[is_foll] &= (dist_foll_to_inter <= gradient_inner)
    # Outer gradient band (0-gradient_outer px outside foll boundary)
    outer_gradient = (~is_foll).copy()
    outer_gradient[~is_foll] &= (dist_inter_to_foll <= gradient_outer)

    n_ig = np.sum(inner_gradient)
    n_og = np.sum(outer_gradient)

    if n_ig < 5 or n_og < 5:
        gradient_sharpness = np.nan
    else:
        mean_cd20_inner = np.mean(cd20_roi[inner_gradient])
        mean_cd20_outer = np.mean(cd20_roi[outer_gradient])
        gradient_sharpness = mean_cd20_inner - mean_cd20_outer

    # Boundary cell mask for visualization
    boundary_mask = inner_band | outer_band
    n_boundary = np.sum(boundary_mask)

    return {
        'ratio_sharpness': ratio_sharpness,
        'gradient_sharpness': gradient_sharpness,
        'n_boundary_cells': n_boundary,
        'b_frac_inner': b_frac_inner,
        'b_frac_outer': b_frac_outer,
        'n_inner': n_inner,
        'n_outer': n_outer,
        'inner_band': inner_band,
        'outer_band': outer_band,
    }


# ---------------------------------------------------------------------------
# Follicularity and entropy per ROI
# ---------------------------------------------------------------------------
def compute_follicularity(sample_ids_roi, domains_roi, foll_domains):
    """Fraction of cells in follicular domains."""
    is_foll = np.isin(domains_roi, foll_domains)
    return np.sum(is_foll) / len(domains_roi) if len(domains_roi) > 0 else 0.0


def compute_clean_entropy(cell_types_roi):
    """Shannon entropy excluding LQ/Unassigned cells."""
    clean = cell_types_roi[~np.isin(cell_types_roi, list(LQ_TYPES))]
    if len(clean) < 20:
        return np.nan
    counts = Counter(clean)
    total = sum(counts.values())
    props = np.array([c / total for c in counts.values()])
    props = props[props > 0]
    return -np.sum(props * np.log2(props))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print(f"{'='*70}")
    print(f"H1a: Follicle Boundary Sharpness — S-panel")
    print(f"{'='*70}")

    # Generate concept cartoon
    cartoon_path = generate_cartoon()

    # Load data
    print("\nLoading S-panel v8 data...")
    f_v8 = h5py.File(V8_PATH, 'r')
    f_utag = h5py.File(UTAG_PATH, 'r')

    sample_ids = load_array(f_v8, 'sample_id')
    tma_arr = load_array(f_v8, 'tma')
    cell_types = load_array(f_v8, 'cell_type')
    cx = f_v8['obs']['centroid_x'][:]
    cy = f_v8['obs']['centroid_y'][:]
    marker_idx = get_marker_idx(f_v8)

    tumor_mask = get_tumor_mask(sample_ids)
    print(f"Total cells: {len(sample_ids):,}")
    print(f"Tumor cells: {np.sum(tumor_mask):,}")

    # Classify UTAG domains
    print("\nClassifying UTAG domains...")
    domains, foll_domains, inter_domains = classify_domains(f_utag, cell_types, PANEL)

    # Load CD20 marker
    cd20 = load_marker(f_v8, 'CD20', marker_idx)
    print(f"CD20 marker loaded (idx={marker_idx.get('CD20', 'N/A')})")

    # B cell mask (all B cell subtypes)
    b_cell_types = {'B cells', 'B cells (BCL2+)', 'B cells (PAX5+)'}
    b_cell_mask = np.isin(cell_types, list(b_cell_types))
    print(f"B cells: {np.sum(b_cell_mask & tumor_mask):,}")

    # FDC mask
    fdc_mask = cell_types == 'FDC'
    print(f"FDC cells: {np.sum(fdc_mask & tumor_mask):,}")

    # --- Compute boundary sharpness per ROI ---
    print("\nComputing boundary sharpness per ROI...")
    unique_rois = sorted(set(sample_ids[tumor_mask]))
    roi_data = []  # list of dicts
    skipped_min_cells = 0
    skipped_no_boundary = 0

    for i, roi in enumerate(unique_rois):
        if (i + 1) % 20 == 0:
            print(f"  Processing ROI {i+1}/{len(unique_rois)}...")

        roi_mask = (sample_ids == roi) & tumor_mask
        ct_roi = cell_types[roi_mask]

        # Min cells filter (non-LQ)
        n_typed = np.sum(~np.isin(ct_roi, list(LQ_TYPES)))
        if n_typed < MIN_CELLS:
            skipped_min_cells += 1
            continue

        cx_roi = cx[roi_mask]
        cy_roi = cy[roi_mask]
        domains_roi = domains[roi_mask]
        b_mask_roi = b_cell_mask[roi_mask]
        cd20_roi = cd20[roi_mask]
        fdc_mask_roi = fdc_mask[roi_mask]

        result = compute_boundary_sharpness(
            cx_roi, cy_roi, domains_roi, foll_domains,
            b_mask_roi, cd20_roi
        )

        if result is None:
            skipped_no_boundary += 1
            continue

        # Additional metrics
        tma_val = tma_arr[roi_mask][0]
        follicularity = compute_follicularity(sample_ids[roi_mask], domains_roi, foll_domains)
        entropy = compute_clean_entropy(ct_roi)
        fdc_frac = np.sum(fdc_mask_roi) / n_typed if n_typed > 0 else 0.0

        roi_data.append({
            'roi': roi,
            'tma': tma_val,
            'ratio_sharpness': result['ratio_sharpness'],
            'gradient_sharpness': result['gradient_sharpness'],
            'n_boundary_cells': result['n_boundary_cells'],
            'b_frac_inner': result['b_frac_inner'],
            'b_frac_outer': result['b_frac_outer'],
            'follicularity': follicularity,
            'entropy': entropy,
            'fdc_frac': fdc_frac,
            'n_typed': n_typed,
        })

    print(f"\nROIs processed: {len(roi_data)}")
    print(f"Skipped (min_cells): {skipped_min_cells}")
    print(f"Skipped (no boundary): {skipped_no_boundary}")

    if len(roi_data) < 10:
        print("ERROR: Too few ROIs with boundary data. Aborting.")
        f_v8.close()
        f_utag.close()
        return

    # Extract arrays
    rois = [d['roi'] for d in roi_data]
    tmas = [d['tma'] for d in roi_data]
    ratio_sharp = np.array([d['ratio_sharpness'] for d in roi_data])
    gradient_sharp = np.array([d['gradient_sharpness'] for d in roi_data])
    follicularity = np.array([d['follicularity'] for d in roi_data])
    entropy = np.array([d['entropy'] for d in roi_data])
    fdc_frac = np.array([d['fdc_frac'] for d in roi_data])
    b_frac_inner = np.array([d['b_frac_inner'] for d in roi_data])
    b_frac_outer = np.array([d['b_frac_outer'] for d in roi_data])

    # Use log(ratio) for better distribution
    log_ratio = np.log2(np.clip(ratio_sharp, 0.01, None))

    # --- Summary statistics ---
    print(f"\n{'='*50}")
    print("BOUNDARY SHARPNESS SUMMARY")
    print(f"{'='*50}")
    print(f"Ratio sharpness (B inner/outer): "
          f"mean={np.mean(ratio_sharp):.2f}, median={np.median(ratio_sharp):.2f}, "
          f"std={np.std(ratio_sharp):.2f}, range=[{np.min(ratio_sharp):.2f}, {np.max(ratio_sharp):.2f}]")
    print(f"Log2 ratio: mean={np.mean(log_ratio):.2f}, std={np.std(log_ratio):.2f}")
    valid_grad = ~np.isnan(gradient_sharp)
    print(f"Gradient sharpness (CD20 inner-outer): "
          f"mean={np.nanmean(gradient_sharp):.2f}, std={np.nanstd(gradient_sharp):.2f}, "
          f"n_valid={np.sum(valid_grad)}")
    print(f"B frac inner: mean={np.mean(b_frac_inner):.3f}")
    print(f"B frac outer: mean={np.mean(b_frac_outer):.3f}")

    # --- Correlations ---
    print(f"\n{'='*50}")
    print("CORRELATIONS (Spearman)")
    print(f"{'='*50}")

    # Ratio sharpness vs follicularity
    rho_foll, p_foll = spearmanr(log_ratio, follicularity)
    print(f"Log2(ratio) vs follicularity: rho={rho_foll:.3f}, p={p_foll:.2e}")

    # Ratio sharpness vs entropy
    valid_ent = ~np.isnan(entropy)
    rho_ent, p_ent = spearmanr(log_ratio[valid_ent], entropy[valid_ent])
    print(f"Log2(ratio) vs entropy: rho={rho_ent:.3f}, p={p_ent:.2e}")

    # Ratio sharpness vs FDC fraction
    rho_fdc, p_fdc = spearmanr(log_ratio, fdc_frac)
    print(f"Log2(ratio) vs FDC fraction: rho={rho_fdc:.3f}, p={p_fdc:.2e}")

    # Gradient vs follicularity
    if np.sum(valid_grad) > 10:
        rho_gf, p_gf = spearmanr(gradient_sharp[valid_grad], follicularity[valid_grad])
        print(f"Gradient vs follicularity: rho={rho_gf:.3f}, p={p_gf:.2e}")

    # --- Per-TMA breakdown ---
    print(f"\n{'='*50}")
    print("PER-TMA BREAKDOWN")
    print(f"{'='*50}")
    tma_unique = sorted(set(tmas))
    print(f"{'TMA':>8} {'n':>5} {'mean_ratio':>11} {'median_ratio':>13} {'mean_log2':>10}")
    tma_groups_lr = {}
    for t in tma_unique:
        idx_t = [i for i, tt in enumerate(tmas) if tt == t]
        vals_t = log_ratio[idx_t]
        tma_groups_lr[t] = vals_t
        print(f"{t:>8} {len(idx_t):>5} {np.mean(ratio_sharp[idx_t]):>11.2f} "
              f"{np.median(ratio_sharp[idx_t]):>13.2f} {np.mean(vals_t):>10.2f}")

    # --- Leave-one-TMA-out sensitivity ---
    print(f"\n{'='*50}")
    print("LEAVE-ONE-TMA-OUT SENSITIVITY")
    print(f"{'='*50}")
    loo_results = []
    for exclude in tma_unique:
        idx_keep = [i for i, tt in enumerate(tmas) if tt != exclude]
        lr_keep = log_ratio[idx_keep]
        foll_keep = follicularity[idx_keep]
        ent_keep = entropy[idx_keep]
        fdc_keep = fdc_frac[idx_keep]

        rho_f, p_f = spearmanr(lr_keep, foll_keep)
        valid_e = ~np.isnan(ent_keep)
        rho_e, p_e = spearmanr(lr_keep[valid_e], ent_keep[valid_e]) if np.sum(valid_e) > 5 else (np.nan, np.nan)
        rho_d, p_d = spearmanr(lr_keep, fdc_keep)

        loo_results.append({
            'excluded': exclude,
            'n': len(idx_keep),
            'rho_foll': rho_f, 'p_foll': p_f,
            'rho_ent': rho_e, 'p_ent': p_e,
            'rho_fdc': rho_d, 'p_fdc': p_d,
        })
        print(f"Exclude {exclude} (n={len(idx_keep)}): "
              f"foll rho={rho_f:.3f} p={p_f:.2e}, "
              f"entropy rho={rho_e:.3f} p={p_e:.2e}, "
              f"FDC rho={rho_d:.3f} p={p_d:.2e}")

    # --- Driver analysis ---
    print(f"\n{'='*50}")
    print("DRIVER ANALYSIS (cell type correlations with sharpness)")
    print(f"{'='*50}")
    roi_metric = {d['roi']: lr for d, lr in zip(roi_data, log_ratio)}
    roi_fracs = compute_roi_celltype_fractions(sample_ids, cell_types, tumor_mask, LQ_TYPES)
    drivers = correlate_celltype_with_metric(roi_fracs, roi_metric)
    for ct, rho, p in drivers[:15]:
        print(f"  {ct:40s}  rho={rho:+.3f}  p={p:.2e}")

    # -----------------------------------------------------------------------
    # MAIN FIGURE (2x3)
    # -----------------------------------------------------------------------
    print("\nGenerating main figure...")
    fig, axes = plt.subplots(2, 3, figsize=(18, 11))

    # (a) Concept cartoon
    add_cartoon(axes[0, 0], cartoon_path)
    label_panel(axes[0, 0], 'a')

    # (b) Distribution of boundary sharpness
    ax = axes[0, 1]
    for t in tma_unique:
        idx_t = [i for i, tt in enumerate(tmas) if tt == t]
        ax.hist(log_ratio[idx_t], bins=15, alpha=0.5, color=TMA_COLORS.get(t, 'gray'),
                label=f'{t} (n={len(idx_t)})', edgecolor='white')
    ax.axvline(np.mean(log_ratio), color='black', linestyle='--', lw=1.5,
               label=f'Mean = {np.mean(log_ratio):.2f}')
    ax.axvline(np.median(log_ratio), color='gray', linestyle=':', lw=1.5,
               label=f'Median = {np.median(log_ratio):.2f}')
    ax.set_xlabel('Boundary Sharpness (log2 B-cell ratio)', fontsize=10)
    ax.set_ylabel('Number of ROIs', fontsize=10)
    ax.set_title(f'Distribution of Boundary Sharpness\n(n={len(roi_data)} tumor ROIs)', fontsize=11)
    ax.legend(fontsize=7)
    label_panel(ax, 'b')

    # (c) Scatter: sharpness vs follicularity
    ax = axes[0, 2]
    for t in tma_unique:
        idx_t = [i for i, tt in enumerate(tmas) if tt == t]
        ax.scatter(follicularity[idx_t], log_ratio[idx_t], c=TMA_COLORS.get(t, 'gray'),
                   alpha=0.6, s=25, edgecolors='white', linewidths=0.3, label=t)
    # Add regression line
    z = np.polyfit(follicularity, log_ratio, 1)
    x_line = np.linspace(follicularity.min(), follicularity.max(), 100)
    ax.plot(x_line, np.polyval(z, x_line), 'k--', alpha=0.5, lw=1.5)
    ax.set_xlabel('Follicularity (fraction in follicular domains)', fontsize=10)
    ax.set_ylabel('Boundary Sharpness (log2 ratio)', fontsize=10)
    ax.set_title(f'Sharpness vs Follicularity\n(Spearman rho={rho_foll:.3f}, p={p_foll:.2e})', fontsize=11)
    ax.legend(fontsize=7, loc='best')
    label_panel(ax, 'c')

    # (d) Representative spatial plots: sharp vs diffuse boundary
    ax = axes[1, 0]
    # Find sharp and diffuse ROIs (85th and 15th percentile)
    p15_val = np.percentile(log_ratio, 15)
    p85_val = np.percentile(log_ratio, 85)
    idx_lo = np.argmin(np.abs(log_ratio - p15_val))
    idx_hi = np.argmin(np.abs(log_ratio - p85_val))
    roi_lo = roi_data[idx_lo]['roi']
    roi_hi = roi_data[idx_hi]['roi']

    ax.axis('off')
    ax_lo = ax.inset_axes([0.0, 0.0, 0.47, 0.88])
    ax_hi = ax.inset_axes([0.53, 0.0, 0.47, 0.88])

    for sub_ax, roi_name, val, label in [
        (ax_lo, roi_lo, log_ratio[idx_lo], 'Diffuse'),
        (ax_hi, roi_hi, log_ratio[idx_hi], 'Sharp')
    ]:
        m = (sample_ids == roi_name) & tumor_mask
        x_all, y_all = cx[m], cy[m]
        dom = domains[m]
        ct_all = cell_types[m]
        b_m = b_cell_mask[m]
        is_foll = np.isin(dom, foll_domains)
        is_inter = np.isin(dom, inter_domains)

        # Domain background tint
        if np.any(is_foll):
            sub_ax.scatter(x_all[is_foll], y_all[is_foll], c='#FFDDDD', s=5,
                          alpha=0.3, edgecolors='none', rasterized=True, zorder=0)
        if np.any(is_inter):
            sub_ax.scatter(x_all[is_inter], y_all[is_inter], c='#DDDDFF', s=5,
                          alpha=0.3, edgecolors='none', rasterized=True, zorder=0)

        # All cells as gray
        sub_ax.scatter(x_all, y_all, c='#D3D3D3', s=0.3, alpha=0.4,
                      edgecolors='none', rasterized=True, zorder=1)

        # Compute boundary cells for this ROI
        coords_roi = np.column_stack([x_all, y_all])
        foll_coords = coords_roi[is_foll]
        inter_coords = coords_roi[~is_foll]

        if len(foll_coords) > 0 and len(inter_coords) > 0:
            tree_f = KDTree(foll_coords)
            tree_i = KDTree(inter_coords)
            dist_f2i, _ = tree_i.query(foll_coords, k=1)
            dist_i2f, _ = tree_f.query(inter_coords, k=1)

            boundary_foll = np.zeros(len(x_all), dtype=bool)
            boundary_inter = np.zeros(len(x_all), dtype=bool)
            boundary_foll[is_foll] = dist_f2i <= BAND_WIDTH
            boundary_inter[~is_foll] = dist_i2f <= BAND_WIDTH
            boundary_cells = boundary_foll | boundary_inter

            # Highlight boundary B cells in gold
            highlight = boundary_cells & b_m
            if np.any(highlight):
                sub_ax.scatter(x_all[highlight], y_all[highlight],
                              c='#FFD700', s=12, edgecolors='black',
                              linewidths=0.3, zorder=3, rasterized=True)

        sub_ax.set_aspect('equal')
        sub_ax.invert_yaxis()
        sub_ax.axis('off')
        short = roi_name if len(roi_name) <= 18 else roi_name[:16] + '..'
        sub_ax.set_title(f'{label}\n{short}\nSharpness={val:.2f}', fontsize=7)

    # Legend for (d)
    legend_items = [
        Line2D([0], [0], marker='o', color='w', markerfacecolor='#FFD700',
               markeredgecolor='black', markersize=7, label='Boundary B cells'),
        Patch(facecolor='#FFDDDD', alpha=0.5, label='Follicular zone'),
        Patch(facecolor='#DDDDFF', alpha=0.5, label='Interfollicular'),
    ]
    ax.legend(handles=legend_items, loc='lower center', ncol=3, fontsize=6,
              bbox_to_anchor=(0.5, -0.08), frameon=False)
    ax.set_title('Representative Cores', fontsize=10)
    label_panel(ax, 'd')

    # (e) Scatter: sharpness vs FDC fraction
    ax = axes[1, 1]
    for t in tma_unique:
        idx_t = [i for i, tt in enumerate(tmas) if tt == t]
        ax.scatter(fdc_frac[idx_t], log_ratio[idx_t], c=TMA_COLORS.get(t, 'gray'),
                   alpha=0.6, s=25, edgecolors='white', linewidths=0.3, label=t)
    if np.any(fdc_frac > 0):
        z2 = np.polyfit(fdc_frac, log_ratio, 1)
        x_line2 = np.linspace(fdc_frac.min(), fdc_frac.max(), 100)
        ax.plot(x_line2, np.polyval(z2, x_line2), 'k--', alpha=0.5, lw=1.5)
    ax.set_xlabel('FDC Fraction', fontsize=10)
    ax.set_ylabel('Boundary Sharpness (log2 ratio)', fontsize=10)
    ax.set_title(f'Sharpness vs FDC Fraction\n(Spearman rho={rho_fdc:.3f}, p={p_fdc:.2e})', fontsize=11)
    ax.legend(fontsize=7, loc='best')
    label_panel(ax, 'e')

    # (f) Driver analysis (cell type correlations)
    ax = axes[1, 2]
    top_n = min(12, len(drivers))
    if top_n > 0:
        top = drivers[:top_n]
        names_d = [d[0] for d in reversed(top)]
        rhos_d = [d[1] for d in reversed(top)]
        colors_bar = ['#e74c3c' if r < 0 else '#2ecc71' for r in rhos_d]
        ax.barh(range(len(names_d)), rhos_d, color=colors_bar, alpha=0.8)
        ax.set_yticks(range(len(names_d)))
        ax.set_yticklabels([n[:30] for n in names_d], fontsize=7)
        ax.set_xlabel('Spearman rho', fontsize=10)
        ax.set_title('Cell Type Drivers\n(correlation with sharpness)', fontsize=11)
        ax.axvline(0, color='gray', lw=0.5)
    label_panel(ax, 'f')

    plt.suptitle('H1a: Follicle Boundary Sharpness — S-panel', fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    fig_path = os.path.join(OUTPUT_DIR, 'fig_h1a_S.png')
    plt.savefig(fig_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Main figure saved: {fig_path}")

    # -----------------------------------------------------------------------
    # SUPPLEMENTARY FIGURE (leave-one-TMA-out)
    # -----------------------------------------------------------------------
    print("\nGenerating supplementary figure...")
    fig_supp, axes_supp = plt.subplots(2, 3, figsize=(16, 10))

    # (a) Per-TMA boxplot
    ax = axes_supp[0, 0]
    box_data = [tma_groups_lr.get(t, []) for t in tma_unique]
    bp = ax.boxplot(box_data, tick_labels=tma_unique, patch_artist=True)
    for patch, t in zip(bp['boxes'], tma_unique):
        patch.set_facecolor(TMA_COLORS.get(t, 'gray'))
        patch.set_alpha(0.6)
    ax.set_ylabel('Boundary Sharpness (log2 ratio)')
    ax.set_xlabel('TMA')
    ax.set_title('Per-TMA Distribution')
    label_panel(ax, 'a')

    # (b) Leave-one-out: foll correlation
    ax = axes_supp[0, 1]
    excl_names = [r['excluded'] for r in loo_results]
    pvals_foll = [r['p_foll'] for r in loo_results]
    rhos_foll = [r['rho_foll'] for r in loo_results]
    bar_colors = [TMA_COLORS.get(n, 'gray') for n in excl_names]
    bars = ax.bar(excl_names, rhos_foll, color=bar_colors, alpha=0.7)
    ax.axhline(rho_foll, color='black', linestyle='--', lw=1, label=f'Full cohort (rho={rho_foll:.3f})')
    for i, (rho_v, p_v) in enumerate(zip(rhos_foll, pvals_foll)):
        sig = '***' if p_v < 0.001 else ('**' if p_v < 0.01 else ('*' if p_v < 0.05 else 'n.s.'))
        ax.text(i, rho_v + 0.01, sig, ha='center', fontsize=8)
    ax.set_ylabel('Spearman rho (sharpness vs follicularity)')
    ax.set_xlabel('Excluded TMA')
    ax.set_title('Leave-One-Out: Follicularity')
    ax.legend(fontsize=8)
    label_panel(ax, 'b')

    # (c) Leave-one-out: FDC correlation
    ax = axes_supp[0, 2]
    rhos_fdc_loo = [r['rho_fdc'] for r in loo_results]
    pvals_fdc_loo = [r['p_fdc'] for r in loo_results]
    ax.bar(excl_names, rhos_fdc_loo, color=bar_colors, alpha=0.7)
    ax.axhline(rho_fdc, color='black', linestyle='--', lw=1, label=f'Full cohort (rho={rho_fdc:.3f})')
    for i, (rho_v, p_v) in enumerate(zip(rhos_fdc_loo, pvals_fdc_loo)):
        sig = '***' if p_v < 0.001 else ('**' if p_v < 0.01 else ('*' if p_v < 0.05 else 'n.s.'))
        ax.text(i, rho_v + 0.01 * np.sign(rho_v), sig, ha='center', fontsize=8)
    ax.set_ylabel('Spearman rho (sharpness vs FDC frac)')
    ax.set_xlabel('Excluded TMA')
    ax.set_title('Leave-One-Out: FDC Fraction')
    ax.legend(fontsize=8)
    label_panel(ax, 'c')

    # (d) Gradient sharpness distribution
    ax = axes_supp[1, 0]
    if np.sum(valid_grad) > 0:
        for t in tma_unique:
            idx_t = [i for i, tt in enumerate(tmas) if tt == t and valid_grad[i]]
            if len(idx_t) > 0:
                ax.hist(gradient_sharp[idx_t], bins=15, alpha=0.5,
                        color=TMA_COLORS.get(t, 'gray'), label=t, edgecolor='white')
        ax.axvline(0, color='gray', lw=0.5, linestyle='--')
        ax.set_xlabel('CD20 Gradient (inner - outer)')
        ax.set_ylabel('Number of ROIs')
        ax.set_title('CD20 Gradient Sharpness')
        ax.legend(fontsize=7)
    label_panel(ax, 'd')

    # (e) Scatter: gradient vs ratio sharpness
    ax = axes_supp[1, 1]
    if np.sum(valid_grad) > 10:
        rho_gg, p_gg = spearmanr(log_ratio[valid_grad], gradient_sharp[valid_grad])
        for t in tma_unique:
            idx_t = [i for i, tt in enumerate(tmas) if tt == t and valid_grad[i]]
            if len(idx_t) > 0:
                ax.scatter(log_ratio[idx_t], gradient_sharp[idx_t],
                          c=TMA_COLORS.get(t, 'gray'), alpha=0.6, s=25,
                          edgecolors='white', linewidths=0.3, label=t)
        ax.set_xlabel('Log2 Ratio Sharpness')
        ax.set_ylabel('CD20 Gradient Sharpness')
        ax.set_title(f'Ratio vs Gradient\n(rho={rho_gg:.3f}, p={p_gg:.2e})')
        ax.legend(fontsize=7)
    label_panel(ax, 'e')

    # (f) Leave-one-out: entropy correlation
    ax = axes_supp[1, 2]
    rhos_ent_loo = [r['rho_ent'] for r in loo_results]
    pvals_ent_loo = [r['p_ent'] for r in loo_results]
    ax.bar(excl_names, rhos_ent_loo, color=bar_colors, alpha=0.7)
    ax.axhline(rho_ent, color='black', linestyle='--', lw=1, label=f'Full cohort (rho={rho_ent:.3f})')
    for i, (rho_v, p_v) in enumerate(zip(rhos_ent_loo, pvals_ent_loo)):
        sig = '***' if p_v < 0.001 else ('**' if p_v < 0.01 else ('*' if p_v < 0.05 else 'n.s.'))
        ax.text(i, rho_v + 0.01 * np.sign(rho_v), sig, ha='center', fontsize=8)
    ax.set_ylabel('Spearman rho (sharpness vs entropy)')
    ax.set_xlabel('Excluded TMA')
    ax.set_title('Leave-One-Out: Entropy')
    ax.legend(fontsize=8)
    label_panel(ax, 'f')

    plt.suptitle('H1a: Follicle Boundary Sharpness — S-panel (Supplementary)',
                 fontsize=14, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    supp_path = os.path.join(OUTPUT_DIR, 'fig_h1a_S_supp.png')
    plt.savefig(supp_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Supplementary figure saved: {supp_path}")

    # --- Final assessment ---
    print(f"\n{'='*70}")
    print("HYPOTHESIS H1a ASSESSMENT")
    print(f"{'='*70}")

    # Check significance and consistency
    sig_foll = p_foll < 0.05
    sig_fdc = p_fdc < 0.05
    sig_ent = p_ent < 0.05

    # Check LOO consistency
    loo_foll_consistent = all(r['p_foll'] < 0.05 for r in loo_results)
    loo_fdc_consistent = all(r['p_fdc'] < 0.05 for r in loo_results)

    print(f"Sharpness vs follicularity: rho={rho_foll:.3f}, p={p_foll:.2e} {'SIGNIFICANT' if sig_foll else 'n.s.'}")
    print(f"Sharpness vs FDC fraction:  rho={rho_fdc:.3f}, p={p_fdc:.2e} {'SIGNIFICANT' if sig_fdc else 'n.s.'}")
    print(f"Sharpness vs entropy:       rho={rho_ent:.3f}, p={p_ent:.2e} {'SIGNIFICANT' if sig_ent else 'n.s.'}")
    print(f"LOO consistency (foll):     {'Yes' if loo_foll_consistent else 'No'}")
    print(f"LOO consistency (FDC):      {'Yes' if loo_fdc_consistent else 'No'}")

    if sig_foll and loo_foll_consistent:
        status = "CONFIRMED"
        note = f"Boundary sharpness correlates with follicularity (rho={rho_foll:.3f}, p={p_foll:.2e}), consistent across TMAs"
    elif sig_foll:
        status = "CONFIRMED (partial)"
        note = f"Boundary sharpness correlates with follicularity (rho={rho_foll:.3f}, p={p_foll:.2e}), but not consistent in all LOO"
    elif any(r['p_foll'] < 0.05 for r in loo_results):
        status = "INCONCLUSIVE"
        note = "Some signal but not robust across TMAs"
    else:
        status = "NOT CONFIRMED"
        note = "No significant correlation"

    print(f"\nSTATUS: {status}")
    print(f"NOTE: {note}")

    f_v8.close()
    f_utag.close()

    return status, note


if __name__ == '__main__':
    main()
