#!/usr/bin/env python3
"""H3c: CD11c+HLA-DR+ DC-like cells define tolerogenic programs.

Panel: S-panel
Rationale: Dendritic cells in the FL TME may drive tolerance through
immune checkpoint expression and spatial positioning relative to T cell
zones and follicles.

Gating: 'Dendritic cells' cell type from v8 annotations (CD11c+HLA-DR+).
Also examine IDO/VISTA expression (marginal markers) on DCs vs other myeloid.

Tests:
  1. DC density per ROI — distribution across cohort
  2. DC domain enrichment — follicular vs interfollicular (paired Wilcoxon)
  3. DC proximity to T cells vs B cells (KDTree nearest-neighbor distances)
  4. DC fraction correlation with entropy and follicularity
  5. IDO/VISTA expression on DCs vs other myeloid
  6. Cell type drivers of DC fraction
  7. Leave-one-TMA-out sensitivity
"""

import os, sys
import numpy as np
import h5py
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from scipy.stats import spearmanr, mannwhitneyu, wilcoxon, kruskal
from scipy.spatial import KDTree
from collections import Counter

sys.path.insert(0, os.path.join(os.path.dirname(__file__)))
from run_hypotheses_v2 import (
    load_array, get_marker_idx, load_marker, is_tumor_core, get_tumor_mask,
    classify_domains, compute_roi_celltype_fractions, correlate_celltype_with_metric,
    add_cartoon, label_panel, plot_representative_core_spatial,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
V8_PATH = os.path.join(BASE, 'output', 'all_TMA_S_global_v8.h5ad')
UTAG_PATH = os.path.join(BASE, 'output', 'all_TMA_S_utag_ct_merged.h5ad')
OUTPUT_DIR = os.path.join(BASE, 'output', 'hypotheses_v8')
CARTOON_DIR = os.path.join(BASE, 'output', 'hypothesis_cartoons')

PANEL = 'S'
MIN_CELLS = 5000   # S-panel minimum typed cells
MIN_DC = 3          # minimum DCs per ROI for proximity analysis
TMA_COLORS = {'A1': '#3498db', 'B1': '#e74c3c', 'C1': '#2ecc71', 'Biomax': '#f39c12'}
LQ_TYPES = {'Low quality / Unassigned'}

# Cell types for proximity comparison
T_CELL_TYPES = ['CD4 T cells', 'CD8 T cells']
B_CELL_TYPES = ['B cells', 'B cells (BCL2+)', 'B cells (PAX5+)']
MYELOID_TYPES = ['Macrophages', 'M1 Macrophages', 'M2 Macrophages',
                 'Myeloid (S100A9+)', 'Histiocytes (CD44hi)']


# ---------------------------------------------------------------------------
# Generate concept cartoon
# ---------------------------------------------------------------------------
def generate_cartoon():
    cartoon_path = os.path.join(CARTOON_DIR, 'h3c_dc_tolerogenic.png')
    if os.path.exists(cartoon_path):
        print(f"Cartoon already exists: {cartoon_path}")
        return cartoon_path

    os.makedirs(CARTOON_DIR, exist_ok=True)
    print("Generating concept cartoon via Gemini...")
    try:
        from google import genai
        from google.genai import types
        from PIL import Image as PILImage
        import io

        client = genai.Client(api_key=os.environ['GEMINI_API_KEY'])
        prompt = (
            "Scientific concept illustration for a research paper. "
            "Show a simplified tissue section with two zones: a circular follicle "
            "(pale pink region with blue dots representing B cells and a network of "
            "FDC in the center), and a T cell zone (pale blue region with orange "
            "dots representing T cells). "
            "At the interface between the two zones, show larger gold/yellow star-shaped "
            "cells labeled 'DCs (CD11c+HLA-DR+)' positioned strategically at the boundary. "
            "Some DCs have small labels: 'IDO', 'VISTA' near them to indicate tolerogenic "
            "markers. Draw arrows from DCs toward both T cells and B cells indicating "
            "immunosuppressive interactions. "
            "Title at top: 'DC Tolerogenic Niche'. "
            "Clean, schematic style suitable for a biology journal. White background. "
            "Minimal text. Diagrammatic, not photographic."
        )
        response = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(number_of_images=1),
        )
        if response.generated_images:
            img_bytes = response.generated_images[0].image.image_bytes
            img = PILImage.open(io.BytesIO(img_bytes))
            img.save(cartoon_path, format='PNG')
            print(f"Cartoon saved: {cartoon_path}")
        else:
            print("WARNING: No images generated by Gemini")
    except Exception as e:
        print(f"WARNING: Could not generate cartoon: {e}")

    return cartoon_path


# ---------------------------------------------------------------------------
# Shannon entropy (clean, exclude LQ)
# ---------------------------------------------------------------------------
def shannon_entropy(ct_array, lq_types):
    clean = ct_array[~np.isin(ct_array, list(lq_types))]
    if len(clean) < 20:
        return np.nan
    counts = Counter(clean)
    total = sum(counts.values())
    props = np.array([c / total for c in counts.values()])
    props = props[props > 0]
    return float(-np.sum(props * np.log2(props)))


# ---------------------------------------------------------------------------
# Main analysis
# ---------------------------------------------------------------------------
def run_h3c():
    print(f"\n{'='*70}")
    print(f"H3c: CD11c+HLA-DR+ DC-like Cells Define Tolerogenic Programs")
    print(f"{'='*70}")

    # --- Load data ---
    f = h5py.File(V8_PATH, 'r')
    f_utag = h5py.File(UTAG_PATH, 'r')

    sample_ids = load_array(f, 'sample_id')
    tma_arr = load_array(f, 'tma')
    cell_types = load_array(f, 'cell_type')
    tumor_mask = get_tumor_mask(sample_ids)
    cx = f['obs']['centroid_x'][:]
    cy = f['obs']['centroid_y'][:]

    n_total = len(sample_ids)
    n_tumor = np.sum(tumor_mask)
    print(f"S-panel: {n_total:,} total -> {n_tumor:,} tumor cells")

    # DC counts
    is_dc = cell_types == 'Dendritic cells'
    n_dc = np.sum(is_dc & tumor_mask)
    print(f"Dendritic cells in tumor: {n_dc:,} ({n_dc/n_tumor*100:.2f}%)")

    # Non-LQ mask
    non_lq = tumor_mask & ~np.isin(cell_types, list(LQ_TYPES))

    # Load marker data for IDO and VISTA
    marker_idx = get_marker_idx(f)
    ido_vals = load_marker(f, 'IDO', marker_idx)
    vista_vals = load_marker(f, 'VISTA', marker_idx)
    hla_dr_vals = load_marker(f, 'HLA_DR', marker_idx)
    cd11c_vals = load_marker(f, 'CD11c', marker_idx)

    print(f"\nMarker availability:")
    print(f"  IDO: {'loaded' if ido_vals is not None else 'NOT FOUND'}")
    print(f"  VISTA: {'loaded' if vista_vals is not None else 'NOT FOUND'}")
    print(f"  HLA_DR: {'loaded' if hla_dr_vals is not None else 'NOT FOUND'}")
    print(f"  CD11c: {'loaded' if cd11c_vals is not None else 'NOT FOUND'}")

    # Domains
    print(f"\nClassifying UTAG domains...")
    domains, foll_domains, inter_domains = classify_domains(f_utag, cell_types, PANEL)
    foll_mask = np.isin(domains, foll_domains) & tumor_mask
    inter_mask = np.isin(domains, inter_domains) & tumor_mask

    # =========================================================================
    # 1. Per-ROI DC fraction
    # =========================================================================
    print(f"\n--- 1. Per-ROI DC Fraction ---")
    unique_rois = sorted(set(sample_ids[tumor_mask]))
    roi_dc_frac = {}
    roi_dc_count = {}
    roi_tma = {}
    roi_typed_count = {}
    roi_entropy = {}

    for roi in unique_rois:
        rm = (sample_ids == roi) & tumor_mask
        typed = rm & ~np.isin(cell_types, list(LQ_TYPES))
        n_typed = np.sum(typed)

        # Min cells filter: Biomax=5000, others=8000
        tma_val = tma_arr[rm][0]
        min_c = 5000 if 'biomax' in tma_val.lower() else 8000
        if n_typed < min_c:
            continue

        n_dc_roi = np.sum(is_dc & rm)
        roi_dc_frac[roi] = n_dc_roi / n_typed
        roi_dc_count[roi] = n_dc_roi
        roi_tma[roi] = tma_val
        roi_typed_count[roi] = n_typed
        roi_entropy[roi] = shannon_entropy(cell_types[rm], LQ_TYPES)

    n_rois = len(roi_dc_frac)
    dc_fracs = np.array(list(roi_dc_frac.values()))
    print(f"ROIs passing filter: {n_rois}")
    print(f"DC fraction: mean={np.mean(dc_fracs)*100:.2f}%, "
          f"median={np.median(dc_fracs)*100:.2f}%, "
          f"range=[{np.min(dc_fracs)*100:.2f}%, {np.max(dc_fracs)*100:.2f}%]")

    # Per-TMA breakdown
    tmas = sorted(set(roi_tma.values()))
    tma_dc_groups = {}
    print(f"\n  {'TMA':>8} {'n_ROIs':>7} {'mean_DC%':>10} {'std':>8}")
    print("  " + "-" * 40)
    for t in tmas:
        vals = [roi_dc_frac[r] * 100 for r in roi_dc_frac if roi_tma[r] == t]
        tma_dc_groups[t] = vals
        print(f"  {t:>8} {len(vals):>7} {np.mean(vals):>10.2f} {np.std(vals):>8.2f}")

    # KW test across TMAs
    kw_groups = [tma_dc_groups[t] for t in tmas if len(tma_dc_groups[t]) >= 3]
    if len(kw_groups) >= 2:
        H_kw, p_kw = kruskal(*kw_groups)
        print(f"\n  Kruskal-Wallis (DC% across TMAs): H={H_kw:.2f}, p={p_kw:.4f}")
    else:
        p_kw = 1.0

    # =========================================================================
    # 2. DC domain enrichment: follicular vs interfollicular
    # =========================================================================
    print(f"\n--- 2. DC Domain Enrichment ---")
    filtered_rois = sorted(roi_dc_frac.keys())
    roi_dc_foll_frac = {}
    roi_dc_inter_frac = {}

    for roi in filtered_rois:
        rm = (sample_ids == roi) & tumor_mask
        # Follicular
        foll_typed = rm & foll_mask & ~np.isin(cell_types, list(LQ_TYPES))
        n_foll = np.sum(foll_typed)
        n_dc_foll = np.sum(is_dc & rm & foll_mask)
        # Interfollicular
        inter_typed = rm & inter_mask & ~np.isin(cell_types, list(LQ_TYPES))
        n_inter = np.sum(inter_typed)
        n_dc_inter = np.sum(is_dc & rm & inter_mask)

        if n_foll >= 100:
            roi_dc_foll_frac[roi] = n_dc_foll / n_foll
        if n_inter >= 100:
            roi_dc_inter_frac[roi] = n_dc_inter / n_inter

    common_domain_rois = sorted(set(roi_dc_foll_frac.keys()) & set(roi_dc_inter_frac.keys()))
    if len(common_domain_rois) >= 5:
        foll_vals = np.array([roi_dc_foll_frac[r] * 100 for r in common_domain_rois])
        inter_vals = np.array([roi_dc_inter_frac[r] * 100 for r in common_domain_rois])
        # Paired Wilcoxon (within-ROI)
        try:
            stat_w, p_wilcox = wilcoxon(inter_vals, foll_vals, alternative='two-sided')
        except Exception:
            stat_w, p_wilcox = 0, 1.0
        # Also unpaired MWU for robustness
        U_dom, p_dom = mannwhitneyu(inter_vals, foll_vals, alternative='two-sided')
        print(f"  n ROIs with both domains: {len(common_domain_rois)}")
        print(f"  Follicular DC%: mean={np.mean(foll_vals):.3f}%, "
              f"median={np.median(foll_vals):.3f}%")
        print(f"  Interfollicular DC%: mean={np.mean(inter_vals):.3f}%, "
              f"median={np.median(inter_vals):.3f}%")
        if np.mean(foll_vals) > 0:
            print(f"  Ratio (inter/foll): {np.mean(inter_vals)/np.mean(foll_vals):.2f}x")
        print(f"  Wilcoxon signed-rank: stat={stat_w:.0f}, p={p_wilcox:.2e}")
        print(f"  Mann-Whitney U: U={U_dom:.0f}, p={p_dom:.2e}")
    else:
        p_wilcox = 1.0
        p_dom = 1.0
        foll_vals = np.array([])
        inter_vals = np.array([])
        print("  Too few ROIs with both domain types")

    # =========================================================================
    # 3. DC proximity to T cells vs B cells
    # =========================================================================
    print(f"\n--- 3. DC Proximity to T cells vs B cells ---")

    dc_to_t_dists = []   # cell-level DC-to-nearest-T distances
    dc_to_b_dists = []   # cell-level DC-to-nearest-B distances
    dc_nnd_dists = []    # DC-to-DC nearest-neighbor distances (clustering)
    roi_dc_to_t_mean = {}
    roi_dc_to_b_mean = {}
    roi_dc_nnd_mean = {}

    n_skip_prox = 0
    for roi in filtered_rois:
        rm = (sample_ids == roi) & tumor_mask
        dc_mask = is_dc & rm
        n_dc_r = np.sum(dc_mask)
        if n_dc_r < MIN_DC:
            n_skip_prox += 1
            continue

        dc_xy = np.column_stack([cx[dc_mask], cy[dc_mask]])

        # T cells
        t_mask = np.isin(cell_types, T_CELL_TYPES) & rm
        n_t = np.sum(t_mask)
        if n_t >= 3:
            t_xy = np.column_stack([cx[t_mask], cy[t_mask]])
            tree_t = KDTree(t_xy)
            d_t, _ = tree_t.query(dc_xy, k=1)
            dc_to_t_dists.extend(d_t.tolist())
            roi_dc_to_t_mean[roi] = float(np.mean(d_t))

        # B cells
        b_mask = np.isin(cell_types, B_CELL_TYPES) & rm
        n_b = np.sum(b_mask)
        if n_b >= 3:
            b_xy = np.column_stack([cx[b_mask], cy[b_mask]])
            tree_b = KDTree(b_xy)
            d_b, _ = tree_b.query(dc_xy, k=1)
            dc_to_b_dists.extend(d_b.tolist())
            roi_dc_to_b_mean[roi] = float(np.mean(d_b))

        # DC-to-DC NND (spatial clustering)
        if n_dc_r >= 2:
            tree_dc = KDTree(dc_xy)
            d_dc, _ = tree_dc.query(dc_xy, k=2)
            d_dc_nn = d_dc[:, 1]  # skip self (k=0)
            dc_nnd_dists.extend(d_dc_nn.tolist())
            roi_dc_nnd_mean[roi] = float(np.mean(d_dc_nn))

    print(f"ROIs skipped (<{MIN_DC} DCs): {n_skip_prox}")
    dc_to_t_arr = np.array(dc_to_t_dists)
    dc_to_b_arr = np.array(dc_to_b_dists)
    dc_nnd_arr = np.array(dc_nnd_dists)
    print(f"DC-to-T cells: n={len(dc_to_t_arr):,}, "
          f"mean={np.mean(dc_to_t_arr):.1f} px, median={np.median(dc_to_t_arr):.1f} px")
    print(f"DC-to-B cells: n={len(dc_to_b_arr):,}, "
          f"mean={np.mean(dc_to_b_arr):.1f} px, median={np.median(dc_to_b_arr):.1f} px")
    print(f"DC-to-DC NND: n={len(dc_nnd_arr):,}, "
          f"mean={np.mean(dc_nnd_arr):.1f} px, median={np.median(dc_nnd_arr):.1f} px")

    # Paired per-ROI comparison: are DCs closer to T cells or B cells?
    common_prox_rois = sorted(set(roi_dc_to_t_mean.keys()) & set(roi_dc_to_b_mean.keys()))
    if len(common_prox_rois) >= 5:
        t_means = np.array([roi_dc_to_t_mean[r] for r in common_prox_rois])
        b_means = np.array([roi_dc_to_b_mean[r] for r in common_prox_rois])
        try:
            stat_prox, p_prox = wilcoxon(t_means, b_means, alternative='two-sided')
        except Exception:
            stat_prox, p_prox = 0, 1.0
        closer_to = 'T cells' if np.mean(t_means) < np.mean(b_means) else 'B cells'
        print(f"\n  Per-ROI paired comparison (DC-to-T vs DC-to-B):")
        print(f"    Mean DC-to-T: {np.mean(t_means):.1f} px")
        print(f"    Mean DC-to-B: {np.mean(b_means):.1f} px")
        print(f"    DCs are closer to: {closer_to}")
        print(f"    Wilcoxon: stat={stat_prox:.0f}, p={p_prox:.2e}")
    else:
        p_prox = 1.0
        t_means = np.array([])
        b_means = np.array([])
        closer_to = 'N/A'

    # =========================================================================
    # 4. DC fraction vs entropy correlation
    # =========================================================================
    print(f"\n--- 4. DC Fraction vs Entropy ---")
    common_ent_rois = sorted(set(roi_dc_frac.keys()) & set(roi_entropy.keys()))
    valid_ent_rois = [r for r in common_ent_rois if not np.isnan(roi_entropy[r])]
    if len(valid_ent_rois) >= 10:
        dc_frac_arr = np.array([roi_dc_frac[r] for r in valid_ent_rois])
        ent_arr = np.array([roi_entropy[r] for r in valid_ent_rois])
        rho_ent, p_ent = spearmanr(dc_frac_arr, ent_arr)
        print(f"  DC fraction vs entropy: rho={rho_ent:+.3f}, p={p_ent:.2e}")
    else:
        rho_ent, p_ent = 0, 1.0

    # =========================================================================
    # 5. IDO/VISTA expression on DCs vs other myeloid
    # =========================================================================
    print(f"\n--- 5. IDO/VISTA on DCs vs Other Myeloid ---")

    other_myeloid_mask = np.isin(cell_types, MYELOID_TYPES) & tumor_mask
    dc_tumor_mask = is_dc & tumor_mask

    for marker_name, marker_vals in [('IDO', ido_vals), ('VISTA', vista_vals)]:
        if marker_vals is None:
            print(f"  {marker_name}: not available")
            continue
        dc_expr = marker_vals[dc_tumor_mask]
        myeloid_expr = marker_vals[other_myeloid_mask]
        print(f"\n  {marker_name}:")
        print(f"    DCs (n={len(dc_expr):,}): mean={np.mean(dc_expr):.3f}, "
              f"median={np.median(dc_expr):.3f}")
        print(f"    Other myeloid (n={len(myeloid_expr):,}): mean={np.mean(myeloid_expr):.3f}, "
              f"median={np.median(myeloid_expr):.3f}")
        if len(dc_expr) >= 10 and len(myeloid_expr) >= 10:
            U_m, p_m = mannwhitneyu(dc_expr, myeloid_expr, alternative='two-sided')
            print(f"    MWU: U={U_m:.0f}, p={p_m:.2e}")
            if np.median(myeloid_expr) > 0:
                print(f"    Ratio (DC/myeloid median): "
                      f"{np.median(dc_expr)/np.median(myeloid_expr):.2f}x")

    # Also check HLA-DR and CD11c to confirm DC identity
    for marker_name, marker_vals in [('HLA_DR', hla_dr_vals), ('CD11c', cd11c_vals)]:
        if marker_vals is None:
            continue
        dc_expr = marker_vals[dc_tumor_mask]
        myeloid_expr = marker_vals[other_myeloid_mask]
        print(f"\n  {marker_name} (identity check):")
        print(f"    DCs: mean={np.mean(dc_expr):.3f}, "
              f"Other myeloid: mean={np.mean(myeloid_expr):.3f}")

    # =========================================================================
    # 6. Cell type drivers of DC fraction
    # =========================================================================
    print(f"\n--- 6. Cell Type Drivers of DC Fraction ---")
    roi_fracs = compute_roi_celltype_fractions(sample_ids, cell_types, tumor_mask, LQ_TYPES)
    drivers = correlate_celltype_with_metric(roi_fracs, roi_dc_frac)

    print(f"Drivers of DC fraction (Spearman rho):")
    for ct_name, rho, p in drivers[:15]:
        print(f"  {ct_name:40s}  rho={rho:+.3f}  p={p:.2e}")

    # =========================================================================
    # 7. Leave-one-TMA-out sensitivity
    # =========================================================================
    print(f"\n--- 7. Leave-One-TMA-Out Sensitivity ---")
    loo_results = []
    for excl in tmas:
        rois_keep = [r for r in filtered_rois if roi_tma[r] != excl]
        if len(rois_keep) < 5:
            loo_results.append((excl, 1.0, 1.0, 0.0))
            continue

        # Domain enrichment
        common_k = [r for r in rois_keep if r in roi_dc_foll_frac and r in roi_dc_inter_frac]
        if len(common_k) >= 5:
            fv = np.array([roi_dc_foll_frac[r] * 100 for r in common_k])
            iv = np.array([roi_dc_inter_frac[r] * 100 for r in common_k])
            try:
                _, p_loo_dom = wilcoxon(iv, fv, alternative='two-sided')
            except Exception:
                _, p_loo_dom = 0, 1.0
        else:
            p_loo_dom = 1.0

        # Proximity test
        common_prox_k = [r for r in rois_keep
                         if r in roi_dc_to_t_mean and r in roi_dc_to_b_mean]
        if len(common_prox_k) >= 5:
            tm = np.array([roi_dc_to_t_mean[r] for r in common_prox_k])
            bm = np.array([roi_dc_to_b_mean[r] for r in common_prox_k])
            try:
                _, p_loo_prox = wilcoxon(tm, bm, alternative='two-sided')
            except Exception:
                _, p_loo_prox = 0, 1.0
        else:
            p_loo_prox = 1.0

        # Entropy correlation
        ent_k = [r for r in rois_keep
                 if r in roi_dc_frac and r in roi_entropy and not np.isnan(roi_entropy[r])]
        if len(ent_k) >= 10:
            rho_k, _ = spearmanr(
                [roi_dc_frac[r] for r in ent_k],
                [roi_entropy[r] for r in ent_k])
        else:
            rho_k = 0.0

        print(f"  Excl {excl} (n={len(rois_keep)}): "
              f"domain p={p_loo_dom:.2e}, prox p={p_loo_prox:.2e}, "
              f"ent rho={rho_k:+.3f}")
        loo_results.append((excl, p_loo_dom, p_loo_prox, rho_k))

    # =========================================================================
    # Generate cartoon
    # =========================================================================
    cartoon_path = generate_cartoon()

    # =========================================================================
    # MAIN FIGURE: 2 x 3
    # =========================================================================
    print(f"\n--- Generating Main Figure ---")
    fig, axes = plt.subplots(2, 3, figsize=(18, 11))

    # (a) Concept cartoon
    add_cartoon(axes[0, 0], cartoon_path)
    label_panel(axes[0, 0], 'a')

    # (b) DC fraction vs entropy scatter
    ax = axes[0, 1]
    if len(valid_ent_rois) >= 10:
        for roi in valid_ent_rois:
            c = TMA_COLORS.get(roi_tma.get(roi, ''), '#999999')
            ax.scatter(roi_dc_frac[roi] * 100, roi_entropy[roi],
                       c=c, s=30, alpha=0.6, edgecolors='white', linewidths=0.3)
        # Regression line
        x_arr = np.array([roi_dc_frac[r] * 100 for r in valid_ent_rois])
        y_arr = np.array([roi_entropy[r] for r in valid_ent_rois])
        z = np.polyfit(x_arr, y_arr, 1)
        x_line = np.linspace(x_arr.min(), x_arr.max(), 100)
        ax.plot(x_line, np.polyval(z, x_line), 'k--', lw=1, alpha=0.5)
        sig_ent = '***' if p_ent < 0.001 else '**' if p_ent < 0.01 else '*' if p_ent < 0.05 else 'n.s.'
        ax.set_xlabel('DC % of typed cells')
        ax.set_ylabel('Shannon Entropy (bits)')
        ax.set_title(f'DC Fraction vs Entropy\n'
                     f'rho={rho_ent:+.3f}, p={p_ent:.2e} {sig_ent}')
        tma_handles = [Line2D([0], [0], marker='o', color='w', markerfacecolor=c,
                              markersize=7, label=t) for t, c in TMA_COLORS.items()]
        ax.legend(handles=tma_handles, fontsize=7, loc='best')
    else:
        ax.text(0.5, 0.5, 'Insufficient data', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'b')

    # (c) DC domain enrichment (follicular vs interfollicular box plot)
    ax = axes[0, 2]
    if len(foll_vals) > 0 and len(inter_vals) > 0:
        bp = ax.boxplot([foll_vals, inter_vals],
                        tick_labels=['Follicular', 'Interfollicular'],
                        patch_artist=True, widths=0.5)
        bp['boxes'][0].set_facecolor('#FFDDDD')
        bp['boxes'][0].set_edgecolor('#CC4444')
        bp['boxes'][1].set_facecolor('#DDDDFF')
        bp['boxes'][1].set_edgecolor('#4444CC')
        for median in bp['medians']:
            median.set_color('black')
            median.set_linewidth(2)

        # Overlay individual ROI data points
        jitter_f = np.random.normal(1, 0.04, len(foll_vals))
        jitter_i = np.random.normal(2, 0.04, len(inter_vals))
        for roi_idx, roi in enumerate(common_domain_rois):
            c = TMA_COLORS.get(roi_tma.get(roi, ''), '#999999')
            ax.scatter(jitter_f[roi_idx], foll_vals[roi_idx], c=c, s=15,
                       alpha=0.5, edgecolors='white', linewidths=0.3, zorder=3)
            ax.scatter(jitter_i[roi_idx], inter_vals[roi_idx], c=c, s=15,
                       alpha=0.5, edgecolors='white', linewidths=0.3, zorder=3)

        ax.set_ylabel('DC % of typed cells')
        sig_dom_label = ('***' if p_wilcox < 0.001 else '**' if p_wilcox < 0.01
                         else '*' if p_wilcox < 0.05 else 'n.s.')
        ax.set_title(f'DC Domain Enrichment\nWilcoxon p={p_wilcox:.2e} {sig_dom_label}')

        # Significance bracket
        ymax = max(np.max(foll_vals), np.max(inter_vals))
        ax.plot([1, 1, 2, 2], [ymax*1.05, ymax*1.1, ymax*1.1, ymax*1.05], 'k-', lw=1)
        ax.text(1.5, ymax*1.12, sig_dom_label, ha='center', fontsize=11, fontweight='bold')
        ax.set_ylim(top=ymax * 1.25)
    else:
        ax.text(0.5, 0.5, 'Insufficient data', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'c')

    # (d) Representative cores (low vs high DC density)
    ax = axes[1, 0]
    plot_representative_core_spatial(
        ax, cx, cy, sample_ids, cell_types, tumor_mask,
        roi_dc_frac, label_lo='Low DC', label_hi='High DC',
        metric_name='DC%', top_n_types=10,
        domains=domains, foll_domains=foll_domains,
        highlight_mask=is_dc & tumor_mask,
        highlight_label='Dendritic cells',
        highlight_color='#FFD700', min_cells=MIN_CELLS,
        highlight_size=20, min_highlight_hi=5)
    label_panel(ax, 'd')

    # (e) DC proximity to T cells vs B cells (paired comparison per ROI)
    ax = axes[1, 1]
    if len(common_prox_rois) >= 5:
        # Paired lines showing per-ROI DC-to-T vs DC-to-B
        for roi in common_prox_rois:
            c = TMA_COLORS.get(roi_tma.get(roi, ''), '#999999')
            ax.plot([1, 2], [roi_dc_to_t_mean[roi], roi_dc_to_b_mean[roi]],
                    c=c, alpha=0.2, lw=0.5)
            ax.scatter([1], [roi_dc_to_t_mean[roi]], c=c, s=10, alpha=0.4, zorder=3)
            ax.scatter([2], [roi_dc_to_b_mean[roi]], c=c, s=10, alpha=0.4, zorder=3)

        # Overlay means
        mean_t_all = np.mean([roi_dc_to_t_mean[r] for r in common_prox_rois])
        mean_b_all = np.mean([roi_dc_to_b_mean[r] for r in common_prox_rois])
        ax.plot([1, 2], [mean_t_all, mean_b_all], 'k-', lw=3, zorder=4)
        ax.scatter([1, 2], [mean_t_all, mean_b_all], c='black', s=80, zorder=5, marker='D')

        ax.set_xticks([1, 2])
        ax.set_xticklabels(['DC-to-T cells', 'DC-to-B cells'])
        ax.set_ylabel('Mean NND (pixels)')
        sig_prox = ('***' if p_prox < 0.001 else '**' if p_prox < 0.01
                     else '*' if p_prox < 0.05 else 'n.s.')
        ax.set_title(f'DC Proximity: T cells vs B cells\n'
                     f'Wilcoxon p={p_prox:.2e} {sig_prox}\n'
                     f'(closer to {closer_to})')
    else:
        ax.text(0.5, 0.5, 'Insufficient data', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'e')

    # (f) Cell type drivers of DC fraction
    ax = axes[1, 2]
    top_n = min(12, len(drivers))
    if top_n > 0:
        top = drivers[:top_n]
        names = [d[0] for d in reversed(top)]
        rhos = [d[1] for d in reversed(top)]
        colors_bar = ['#e74c3c' if r < 0 else '#2ecc71' for r in rhos]
        ax.barh(range(len(names)), rhos, color=colors_bar, alpha=0.8)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=7)
        ax.set_xlabel('Spearman rho')
        ax.set_title('DC Fraction Drivers\n(cell type rho with DC%)')
        ax.axvline(0, color='gray', lw=0.5)
    else:
        ax.text(0.5, 0.5, 'No drivers found', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'f')

    plt.suptitle('H3c: CD11c+HLA-DR+ DC-like Cells Define Tolerogenic Programs '
                 '-- S-panel\n(pooled tumor cohort, all TMAs)',
                 fontsize=13, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    fig_path = os.path.join(OUTPUT_DIR, 'fig_h3c_S.png')
    plt.savefig(fig_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\nMain figure saved: {fig_path}")

    # =========================================================================
    # SUPPLEMENTARY FIGURE: Leave-one-TMA-out + per-TMA DC density + IDO/VISTA
    # =========================================================================
    print(f"\n--- Generating Supplementary Figure ---")
    fig_s, axes_s = plt.subplots(2, 3, figsize=(16, 10))

    # (a) Per-TMA DC fraction boxplot
    ax = axes_s[0, 0]
    box_data = [tma_dc_groups.get(t, []) for t in tmas]
    bp_s = ax.boxplot(box_data, tick_labels=tmas, patch_artist=True, widths=0.5)
    for patch, t in zip(bp_s['boxes'], tmas):
        patch.set_facecolor(TMA_COLORS.get(t, '#999'))
        patch.set_alpha(0.7)
    for median in bp_s['medians']:
        median.set_color('black')
        median.set_linewidth(2)
    ax.set_ylabel('DC % of typed cells')
    ax.set_xlabel('TMA')
    ax.set_title(f'DC Density per TMA\nKW p={p_kw:.4f}')
    label_panel(ax, 'a')

    # (b) LOO domain enrichment
    ax = axes_s[0, 1]
    if loo_results:
        excl_names = [r[0] for r in loo_results]
        p_loo_vals = [r[1] for r in loo_results]
        colors_loo = [TMA_COLORS.get(t, '#999') for t in excl_names]
        ax.bar(excl_names, [-np.log10(max(p, 1e-300)) for p in p_loo_vals],
               color=colors_loo, alpha=0.7)
        ax.axhline(-np.log10(0.05), color='red', linestyle='--', lw=1,
                   label='p=0.05')
        ax.set_ylabel('-log10(p)')
        ax.set_xlabel('Excluded TMA')
        ax.set_title('LOO: Domain Enrichment Test')
        ax.legend(fontsize=8)
    label_panel(ax, 'b')

    # (c) LOO proximity test
    ax = axes_s[0, 2]
    if loo_results:
        excl_names = [r[0] for r in loo_results]
        p_loo_prox_vals = [r[2] for r in loo_results]
        colors_loo = [TMA_COLORS.get(t, '#999') for t in excl_names]
        ax.bar(excl_names, [-np.log10(max(p, 1e-300)) for p in p_loo_prox_vals],
               color=colors_loo, alpha=0.7)
        ax.axhline(-np.log10(0.05), color='red', linestyle='--', lw=1,
                   label='p=0.05')
        ax.set_ylabel('-log10(p)')
        ax.set_xlabel('Excluded TMA')
        ax.set_title('LOO: Proximity Test (T vs B)')
        ax.legend(fontsize=8)
    label_panel(ax, 'c')

    # (d) IDO expression: DCs vs other myeloid (violin or boxplot)
    ax = axes_s[1, 0]
    if ido_vals is not None:
        dc_ido = ido_vals[dc_tumor_mask]
        myeloid_ido = ido_vals[other_myeloid_mask]
        # Subsample for plotting if too large
        max_pts = 5000
        dc_ido_plot = dc_ido if len(dc_ido) <= max_pts else np.random.choice(dc_ido, max_pts, replace=False)
        my_ido_plot = myeloid_ido if len(myeloid_ido) <= max_pts else np.random.choice(myeloid_ido, max_pts, replace=False)

        bp_ido = ax.boxplot([dc_ido_plot, my_ido_plot],
                            tick_labels=['Dendritic cells', 'Other myeloid'],
                            patch_artist=True, widths=0.5, showfliers=False)
        bp_ido['boxes'][0].set_facecolor('#FFD700')
        bp_ido['boxes'][0].set_alpha(0.7)
        bp_ido['boxes'][1].set_facecolor('#95A5A6')
        bp_ido['boxes'][1].set_alpha(0.7)
        for median in bp_ido['medians']:
            median.set_color('black')
            median.set_linewidth(2)
        # Overlay jittered points
        j1 = np.random.normal(1, 0.06, len(dc_ido_plot))
        j2 = np.random.normal(2, 0.06, len(my_ido_plot))
        ax.scatter(j1, dc_ido_plot, c='#FFD700', s=2, alpha=0.15, zorder=0)
        ax.scatter(j2, my_ido_plot, c='#95A5A6', s=2, alpha=0.15, zorder=0)
        U_ido, p_ido = mannwhitneyu(dc_ido, myeloid_ido, alternative='two-sided')
        sig_ido = '***' if p_ido < 0.001 else '**' if p_ido < 0.01 else '*' if p_ido < 0.05 else 'n.s.'
        ax.set_ylabel('IDO expression (scaled)')
        ax.set_title(f'IDO: DCs vs Other Myeloid\np={p_ido:.2e} {sig_ido}')
    else:
        ax.text(0.5, 0.5, 'IDO not available', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'd')

    # (e) VISTA expression: DCs vs other myeloid
    ax = axes_s[1, 1]
    if vista_vals is not None:
        dc_vista = vista_vals[dc_tumor_mask]
        myeloid_vista = vista_vals[other_myeloid_mask]
        max_pts = 5000
        dc_vista_plot = dc_vista if len(dc_vista) <= max_pts else np.random.choice(dc_vista, max_pts, replace=False)
        my_vista_plot = myeloid_vista if len(myeloid_vista) <= max_pts else np.random.choice(myeloid_vista, max_pts, replace=False)

        bp_vista = ax.boxplot([dc_vista_plot, my_vista_plot],
                              tick_labels=['Dendritic cells', 'Other myeloid'],
                              patch_artist=True, widths=0.5, showfliers=False)
        bp_vista['boxes'][0].set_facecolor('#FFD700')
        bp_vista['boxes'][0].set_alpha(0.7)
        bp_vista['boxes'][1].set_facecolor('#95A5A6')
        bp_vista['boxes'][1].set_alpha(0.7)
        for median in bp_vista['medians']:
            median.set_color('black')
            median.set_linewidth(2)
        j1 = np.random.normal(1, 0.06, len(dc_vista_plot))
        j2 = np.random.normal(2, 0.06, len(my_vista_plot))
        ax.scatter(j1, dc_vista_plot, c='#FFD700', s=2, alpha=0.15, zorder=0)
        ax.scatter(j2, my_vista_plot, c='#95A5A6', s=2, alpha=0.15, zorder=0)
        U_vista, p_vista = mannwhitneyu(dc_vista, myeloid_vista, alternative='two-sided')
        sig_vista = '***' if p_vista < 0.001 else '**' if p_vista < 0.01 else '*' if p_vista < 0.05 else 'n.s.'
        ax.set_ylabel('VISTA expression (scaled)')
        ax.set_title(f'VISTA: DCs vs Other Myeloid\np={p_vista:.2e} {sig_vista}')
    else:
        ax.text(0.5, 0.5, 'VISTA not available', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'e')

    # (f) DC spatial clustering: NND distribution
    ax = axes_s[1, 2]
    if len(dc_nnd_arr) > 0:
        ax.hist(dc_nnd_arr, bins=50, color='#FFD700', alpha=0.7, edgecolor='white',
                density=True)
        ax.axvline(np.mean(dc_nnd_arr), color='red', linestyle='--', lw=1.5,
                   label=f'Mean={np.mean(dc_nnd_arr):.1f} px')
        ax.axvline(np.median(dc_nnd_arr), color='orange', linestyle=':', lw=1.5,
                   label=f'Median={np.median(dc_nnd_arr):.1f} px')
        ax.set_xlabel('DC-to-DC NND (pixels)')
        ax.set_ylabel('Density')
        ax.set_title('DC Spatial Clustering\n(nearest-neighbor distance)')
        ax.legend(fontsize=8)
        ax.set_xlim(0, min(np.percentile(dc_nnd_arr, 99), 300))
    else:
        ax.text(0.5, 0.5, 'No DC NND data', ha='center', va='center',
                transform=ax.transAxes)
    label_panel(ax, 'f')

    plt.suptitle('H3c Supplementary: Per-TMA Sensitivity & Marker Analysis',
                 fontsize=12, fontweight='bold')
    plt.tight_layout(rect=[0, 0, 1, 0.93])
    fig_s_path = os.path.join(OUTPUT_DIR, 'fig_h3c_S_supp.png')
    plt.savefig(fig_s_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Supplementary figure saved: {fig_s_path}")

    # =========================================================================
    # Summary
    # =========================================================================
    print(f"\n{'='*70}")
    print(f"H3c SUMMARY")
    print(f"{'='*70}")
    print(f"Dendritic cells in tumor: {n_dc:,} ({n_dc/n_tumor*100:.2f}%)")
    print(f"ROIs analyzed: {n_rois}")
    print(f"DC fraction: mean={np.mean(dc_fracs)*100:.2f}%, "
          f"median={np.median(dc_fracs)*100:.2f}%")

    if len(foll_vals) > 0 and len(inter_vals) > 0:
        if np.mean(foll_vals) > 0:
            ratio_dom = np.mean(inter_vals) / np.mean(foll_vals)
        else:
            ratio_dom = float('inf')
        enriched_in = 'interfollicular' if ratio_dom > 1 else 'follicular'
        print(f"\nDomain enrichment: {enriched_in} ({ratio_dom:.2f}x, "
              f"Wilcoxon p={p_wilcox:.2e})")

    if len(t_means) > 0 and len(b_means) > 0:
        print(f"DC proximity: closer to {closer_to} "
              f"(T={np.mean(t_means):.1f} vs B={np.mean(b_means):.1f} px, p={p_prox:.2e})")

    print(f"DC fraction vs entropy: rho={rho_ent:+.3f}, p={p_ent:.2e}")

    # LOO stability
    loo_dom_stable = all(r[1] < 0.05 for r in loo_results)
    loo_prox_stable = all(r[2] < 0.05 for r in loo_results)
    print(f"\nLOO stability:")
    print(f"  Domain enrichment: {'STABLE' if loo_dom_stable else 'VARIABLE'}")
    print(f"  Proximity test: {'STABLE' if loo_prox_stable else 'VARIABLE'}")

    # Determine status
    confirmed_criteria = []
    if len(foll_vals) > 0 and p_wilcox < 0.05:
        confirmed_criteria.append('domain_enrichment')
    if len(t_means) > 0 and p_prox < 0.05:
        confirmed_criteria.append('proximity_pattern')
    if p_ent < 0.05 and abs(rho_ent) > 0.2:
        confirmed_criteria.append('entropy_correlation')

    if len(confirmed_criteria) >= 2:
        status = 'CONFIRMED'
    elif len(confirmed_criteria) == 1:
        status = 'PARTIALLY CONFIRMED'
    else:
        status = 'NOT CONFIRMED'

    print(f"\nSTATUS: {status}")
    print(f"  Criteria met: {confirmed_criteria}")
    print(f"{'='*70}")

    f.close()
    f_utag.close()

    return {
        'status': status,
        'n_dc': n_dc,
        'n_rois': n_rois,
        'mean_dc_frac': float(np.mean(dc_fracs)),
        'p_domain': p_wilcox,
        'p_proximity': p_prox,
        'closer_to': closer_to,
        'rho_entropy': rho_ent,
        'p_entropy': p_ent,
        'confirmed_criteria': confirmed_criteria,
    }


if __name__ == '__main__':
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(CARTOON_DIR, exist_ok=True)
    results = run_h3c()
